# INTRODUZIONE

## La guerra e l’opinione pubblica 

La guerra in Ucraina rappresenta un evento senza precedenti nella storia postbellica europea, per almeno quattro ragioni. La prima è proprio il fatto di essere una “guerra.”^[Secondo una delle più citate definizioni operative di guerra interstatale (o intra-sistemica, da distinguersi da quelle extra-statali e civili), quella del *Correlates of War*, è tale un conflitto che ha tre caratteristiche: è combattuto tra stati sovrani e riconosciuti dalla comunità internazionale come tali, vi siano almeno 1.000 morti in battaglia tra tutti gli stati coinvolti, e ciascun singolo partecipante soddisfi uno dei seguenti due requisiti: a) 100 morti in battaglia oppure b) un minimo di 1000 unità attive in combattimento nel teatro di guerra. Se poi la guerra dura più di un anno i morti in battaglia devono raggiungere una media annuale di 1000 casi (cf. @Small-Singer1982 :56; @Sarkees, nd: 3).] In un’epoca in cui la frequenza delle guerre convenzionali è sensibilmente diminuita, a favore di altre forme di conflitto (@Sarkees-Wayman-Singer2003), in particolare in Europa (e.g. @Gaddis1986) ^[Vi è un intenso dibattito sul fatto se le guerre interstatali siano effettivamente declinate (ad es. @Pinker2011) o meno (ad es. @Braumoeller2019). Per una discussione si veda @Gleditsch-Pinker-Thayer-Levy-Thompson2013. Il *Correlates of War Project* registra, nel periodo 1945-2007, una sola guerra interstatale – come definita dal COW – combattuta dalla Russia a fronte delle 40 che questo paese ha condotto tra gli inizi del ‘600 e il 1945.] la guerra ucraina rappresenta un tipico conflitto interstatale condotto con strumenti bellici convenzionali e secondo tattiche più vicine a quelle della Seconda Guerra Mondiale che a quelle tipiche delle guerre post-1945. 

Una seconda novità è che la guerra si svolga in Europa. Per la prima volta dalla fine della Guerra Fredda, una guerra convenzionale si combatte sul suolo del nostro continente. Durante la Guerra Fredda, le poche occasioni in cui i paesi europei, gli Stati Uniti e la Russia si sono fronteggiate in Europa con la minaccia del ricorso all’uso della forza non sono mai sfociate in un conflitto armato. Tipicamente, le guerre interstatali erano combattute in altre regioni del mondo, Inoltre, sono stati più spesso gli Stati Uniti ad essere invischiati in un conflitto (ad esempio in Corea e Vietnam), con i sovietici a sostenere la parte avversa.^[La comparazione con l’Afghanistan è inappropriata, non solo perché non avviene in Europa, ma anche perché in quel caso l’intervento militare sovietico era diretto a sostenere un governo considerato amico, con gli americani che aiutavano invece gli avversari del regime afghano al potere (Litwak, 1992).]. In questo caso, invece, è la Russia ad essere impegnata in prima persona in una guerra interstatale contro l’Ucraina, sostenuta quest’ultima da Europa e Stati Uniti. 

Una terza novità è la *coesione* della risposta dei paesi NATO all’attacco russo. Nel dopoguerra, raramente i paesi europei e gli Stati Uniti si sono trovati completamente *eye-to-eye* quando si trattava di decidere che fare nei confronti alla Russia. A partire dalla guerra di Corea, con il timore del ricorso all’arma atomica da parte americana per fronteggiare la Cina, passando per la crisi degli Euromissili dei primi anni ’80, gli europei si sono trovati spesso su posizioni dissonanti rispetto agli Stati Uniti nella valutazione della gravità della minaccia russa e nella scelta del modo migliore di fronteggiarla. In questo caso invece, almeno sinora, Stati Uniti e paesi europei hanno mostrato una sorprendente coesione nel sostenere l’Ucraina, economicamente e militarmente e nell’accettare i costi economici e politici di questa scelta.

È quindi stato abbastanza naturale, una volta compreso che la guerra sarebbe durata a lungo, che l’attenzione dei politici, degli osservatori e dei media si concentrasse sulle capacità di tenuta della coalizione occidentale. E per spiegare la tenuta di un paese democratico in guerra, l’enfasi si sposta, inevitabilmente, dai decisori politici ai cittadini, dagli eletti ai loro elettori, per saggiare la disponibilità dei secondi a sostenere un conflitto inaspettatamente più prolungato e gravoso di quanto originariamente previsto (@Mueller1971; @Aldrich-et-al2006). E, dal punto di vista della tenuta, l’Italia, tra tutti i grandi paesi europei che sostengono l’Ucraina, ha rappresentato per molti governi ed osservatori ad un tempo una sorpresa ed una fonte di preoccupazione.

<<<<<<< Updated upstream
La quarta ed ultima novità di questo conflitto riguarda infatti proprio *l’Italia*. La determinazione con la quale il governo Draghi prima e quello Meloni dopo hanno appoggiato e dato concreto seguito alle determinazioni prese in sede NATO e UE, senza alcuna incertezza e con grande coerenza, ha sorpreso osservatori e alleati. La sorpresa nasce dal fatto che mentre l’Italia, negli ultimi anni, ha espresso nei confronti della Russia posizioni molto più simpatetiche del resto dei paesi europei, il governo Draghi si è invece immediatamente prodigato con risorse e dichiarazioni a sostegno dell’Ucraina *whatever it takes*. La sorpresa è stata ancora maggiore quando tale linea è stata confermata anche dal governo di centro-destra. Tale coalizione sin dall’inizio del conflitto russo-ucraino, e ancor più durante la campagna elettorale, aveva alimentato, con la crescente vocalità di alcuni dei suoi autorevoli leaders, perplessità e dubbi sulla posizione italiana nel conflitto e sulla capacità di perseguire con coerenza una politica di sostegno all’Ucraina. Perplessità e dubbi che, come vedremo, hanno trovato alimento in settori consistenti della nostra società civile e dell’opinione pubblica. Tuttavia, a più di un anno dall’inizio della legislatura, il governo Meloni sembra proseguire nel solco lasciato da Draghi.
=======
La quarta ed ultima novità di questo conflitto riguarda infatti proprio *l’Italia*. La determinazione con la quale il governo Draghi prima e quello Meloni dopo hanno appoggiato e dato concreto seguito alle determinazioni prese in sede NATO e UE, senza alcuna incertezza e con grande coerenza, ha ad un tempo sorpreso e preoccupato osservatori e alleati. La sorpresa nasce dal fatto che mentre l’Italia, negli ultimi anni, ha espresso nei confronti della Russia posizioni molto più simpatetiche del resto dei paesi europei, il governo Draghi si è invece immediatamente prodigato con risorse e dichiarazioni a sostegno dell’Ucraina *whatever it takes*. La preoccupazione scaturiva dall’aspettativa, poi effettivamente realizzatasi, della vittoria della coalizione di centro-destra alle elezioni del settembre 2022. Tale coalizione, sin dall’inizio del conflitto russo-ucraino e ancor più durante la campagna elettorale, ha alimentato, con la crescente vocalità di alcuni dei suoi autorevoli leaders, perplessità e dubbi sulla posizione italiana nel conflitto e sulla sua capacità di perseguire con coerenza una politica di sostegno all’Ucraina. Perplessità e dubbi che, come vedremo, hanno trovato alimento in settori consistenti della nostra società civile e dell’opinione pubblica. Tuttavia, più di sei mesi dopo l’inizio della legislatura, il governo Meloni sembra continuare nel solco lasciato da Draghi. Ciò peraltro non ha significato un cambiamento radicale dell’opinione pubblica italiana e della sua posizione verso la guerra.
>>>>>>> Stashed changes

Per tutte queste ragioni, accertare cosa gli italiani pensino di questo conflitto e in che misura sostengano o si oppongano allo sforzo a favore del governo ucraino nella sua resistenza alla invasione russa, è un esercizio non solo utile scientificamente ma anche rilevante politicamente. Esso può contribuire infatti a fare chiarezza su molte impressioni e congetture circa le ragioni della scarsa disponibilità dell’opinione pubblica italiana a sostenere il ricorso all’uso della forza militare in quasi ogni circostanza possibile e per comprendere le condizioni in cui tale consenso venga meno o si rafforzi nel caso ucraino (@Everts-e-Isernia2015).

## Indagini, Domande e Comparazioni 

<<<<<<< Updated upstream
Nel tentativo di offrire un quadro articolato e preciso della natura del sostegno (e della opposizione) italiana per la guerra in Ucraina, questo volume ricostruisce gli atteggiamenti dell’opinione pubblica italiana nei confronti di vari aspetti della guerra in Ucraina nel periodo compreso tra febbraio 2022 e giugno 2023.^[Dal 24 febbraio alla fine di giugno 2023, il periodo  coperto da questo rapporto, sono state condotte in Italia decine di indagini al cui interno sono state poste domande relative all’Ucraina. La nostra raccolta sull’Italia raccoglie più di 900 domande poste agli italiani su svariati aspetti della guerra e della sua evoluzione da febbraio 2022 a giugno 2023.] Il volume esamina gli atteggiamenti degli italiani su diversi temi, utilizzando tre ordini di comparazioni: 

- nel tempo, coprendo il periodo tra lo scoppio del conflitto il 24 febbraio 2022 e il 30 giugno 2023;
=======
Nel tentativo di offrire un quadro articolato e preciso della natura del sostegno (e della opposizione) italiana per la guerra in Ucraina, questo rapporto ricostruisce gli atteggiamenti dell’opinione pubblica italiana nei confronti di vari aspetti della guerra in Ucraina nel periodo compreso tra febbraio e giugno 2023. ^[Dal 24 febbraio alla fine di novembre 2022, il periodo  coperto da questo rapporto, sono state condotte in Italia decine di indagini al cui interno sono state poste domande relative all’Ucraina. La *Ukraine public opinion continuity guide* creata dal CIRCaP sull’Italia raccoglie più di 400 domande poste agli italiani su svariati aspetti della guerra e della sua evoluzione da febbraio a novembre 2022.] Il rapporto esamina gli atteggiamenti degli italiani su diversi temi, utilizzando tre ordini di comparazioni: 

- nel tempo, coprendo il periodo tra lo scoppio del conflitto il 24 febbraio e giugno 2023;
>>>>>>> Stashed changes

- nello spazio, rispetto ad altri paesi europei per i quali abbiamo dati disponibili e

- tra formulazioni diverse delle stesse domande.

<<<<<<< Updated upstream
A tale scopo, sono state raccolte tutte le domande rese disponibili sul sito [sondaggipoliticoelettorali.it](http://www.sondaggipoliticoelettorali.it/) e da alcuni istituti di sondaggio (segnatamente IPSOS ed SWG con il bollettino settimanale Radar).^[L’archivio è disponibile online sul sito del CIRCaP e del LAPS dell’Università di Siena.]
=======
Per consentirci tale esame abbiamo raccolto tutte le domande rese disponibili sul sito [sondaggipoliticoelettorali.it](http://www.sondaggipoliticoelettorali.it/) e da alcuni istituti di sondaggio (segnatamente IPSOS ed SWG con il bollettino settimanale Radar.^[L’archivio è disponibile online sul sito del CIRCaP e del LAPS dell’Università di Siena.]
>>>>>>> Stashed changes

La convinzione su cui si fonda questo rapporto è infatti che, accanto alle analisi accurate delle determinanti individuali degli atteggiamenti, sia particolarmente utile una valutazione aggregata delle opinioni del pubblico su tematiche controverse come appunto quelle di politica estera. Guardare alla foresta delle domande disponibili, piuttosto che al singolo albero che di essa fa parte, consente da un lato un apprezzamento dell’effetto – quando c’è – del diverso modo di formulare le domande sugli atteggiamenti degli italiani e, dall’altro lato, consente di far emergere anche alcune interessanti caratteristiche del modo di sondare il pubblico da parte degli istituti di sondaggi italiani. 

Come vedremo, la comparazione tra domande offerte con formulazioni diverse mostra l’importanza che il formato ed il contenuto delle domande hanno su tematiche complesse, caratterizzate da ampi margini di incertezza, nelle quali l’effetto di *framing* esercvita una influenza nell’orientare le risposte degli intervistati. Il problema del c.d. *question wording* lungi dall’essere un fattore di disturbo, una dimostrazione del fatto che con i sondaggi “si può far dire di tutto alla gente,” costituisce invece una fonte preziosa di informazioni, che aiuta a interpretare meglio cosa abbiano in mente gli intervistati quando rispondono ad una domanda e quali argomenti possono indurli a orientare le loro risposte in una direzione piuttosto che l’altra (@Sudman-Bradburn1974).

<<<<<<< Updated upstream
Questa raccolta dice anche qualcosa sul modo in cui gli istituti di sondaggio affrontano temi pubblici attuali e che si prolungano nel tempo, come appunto la guerra Ucraina. Tre ordini di considerazioni appaiono rilevanti a questo proposito. Una prima considerazione è la scarsa comparabilità delle formulazioni delle domande tra istituti diversi. Sebbene le domande sulla guerra in Ucraina siano numerose e coprano aspetti molto differenti, spesso di natura del tutto congiunturale (ad es. singoli eventi, come Butcha), esse sono spesso formulate in maniera diversa e per questo difficilmente comparabili. 

Una seconda osservazione è la scarsa attenzione prestata da molti istituti di sondaggio alla continuità delle domande nel tempo, un aspetto invece, quello dell’analisi delle tendenze dell’opinione pubblica a livello aggregato, particolarmente utile quando si tratta di analizzare un fenomeno che evolve. I pochi trend disponibili sono stati realizzati soprattutto grazie a IPSOS e, in misura minore, a EMG, mentre molto più discontinua e *ad hoc* è stata la produzione di dati da parte di altri istituti. Questa attenzione è inoltre scemata nel corso del tempo. Lo testimonia ad esempio il fatto che IPSOS, l’istituto che insieme a SWG e EMG, ha monitorato con più attenzione le opinioni degli italiani sul conflitto, ha rarefatto il tracking sull’Ucraina dalla fine del 2022 e ora solo sporadicamente pone domande sul tema. 
=======
La sistematica raccolta di informazioni dice anche qualcosa sul modo in cui gli istituti di sondaggio affrontano temi pubblici attuali e prolungati, come appunto la guerra Ucraina. Tre ordini di considerazioni appaiono rilevanti a questo proposito. Una prima considerazione è la scarsa comparabilità delle formulazioni delle domande tra istituti diversi. Sebbene le domande sulla guerra in Ucraina siano numerose e coprano aspetti molto differenti, spesso di natura del tutto congiunturale (ad es. singoli eventi bellici, come Butcha), esse sono spesso formulate in maniera diversa e per questo difficilmente comparabili. 

Una seconda osservazione è la scarsa attenzione prestata da molti istituti di sondaggio alla continuità delle domande nel tempo, un aspetto invece, quello dell’analisi delle tendenze dell’opinione pubblica a livello aggregato, particolarmente utile quando si tratta di analizzare un fenomeno che evolve nel tempo. I pochi trend disponibili sono stati realizzati soprattutto grazie a IPSOS e, in misura minore, a EMG, mentre molto più discontinua e *ad hoc* è stata la produzione di dati da parte di altri istituti. Questa attenzione è scemata nel corso del tempo. Lo testimonia ad esempio il fatto che IPSOS, l’istituto che insieme a SWG e EMG, ha monitorato con più attenzione le opinioni degli italiani sul conflitto, ha dismesso il tracking sull’Ucraina dalla fine del 2022 e ora solo sporadicamente pone domande sul tema. 
>>>>>>> Stashed changes

Infine, va segnalato come la guerra ucraina sia stata oggetto di una certa attenzione *comparata*, con diverse indagini condotte contemporaneamente in più paesi, prevalentemente europei. Si segnalano qui in particolare le indagini eurobarometro (che ha inserito domande sull’Ucraina in diverse indagini nel corso del periodo coperto da questo rapporto) e quelle di SWG (Euroskopia) e YOUGOV. In questo campo sono stati però soprattutto i ricercatori a fornire le informazioni più sistematica, in particolare le rilevazioni EUOpinions e dello European University Institute.

Il rapporto è organizzato per aree tematiche. Esse sono: 

* le preoccupazioni per la guerra e i suoi effetti, sia in assoluto che rispetto ad altre problematiche di politica interna; 

* le cause della guerra e le responsabilità per il suo scoppio, con riferimento anche alla percezione della Russia e di Putin; 

* gli effetti della guerra. Questa sezione si sofferma su tre ordini di temi: 
    * le aspettative circa la sua durata e il suo possibile esito (chi vincerà?), 
    * il rischio di escalation militare (ad esempio con il possibile ricorso alle armi nucleari) e politica (ad es.  con la estensione del conflitto ad altri paesi, segnatamente quelli della NATO;
    * l’atteggiamento verso specifiche richieste da parte ucraina, come quella di una *No-Fly-Zone* nel mese di marzo, o di armi pesanti a partire da aprile 2022.

* Il ruolo del nostro paese nel conflitto, con particolare riferimento sia alla decisione italiana di inviare armi, imporre sanzioni, aumentare le spese militari e, in via del tutto ipotetica, contribuire direttamente con le nostre truppe sia alle decisioni, multilaterali, relative ad una possibile accessione dell’Ucraina alla NATO e all’Unione Europea.

* Gli effetti del conflitto, con particolare riferimento agli effetti economici delle sanzioni e quelli politici dei migranti.

* La percezione del clima di opinione e degli atteggiamenti dei media da parte del pubblico italiano.

Ogni sezione è aperta da una breve sintesi dei risultati, seguita dalle tabelle rilevanti per ciascuna tematica. Ciascuna sezione discute prima alcuni aspetti metodologici relativi al modo in cui sono formulate le domande e ai loro effetti sulle distribuzioni delle risposte, seguite dalla descrizione degli atteggiamenti e della loro evoluzione nel tempo e, quando possibile, comparando le posizioni dell’opinione pubblica italiana a quella di altri paesi.


