# PREOCCUPAZIONE PER LA GUERRA

## Formulazione delle domande 

La misurazione delle preoccupazioni o priorità delle persone risente molto del contenuto e del formato delle domande che vengo poste. Quattro tipi di domande sono state utilizzate nel tempo in Italia per valutare l’importanza della guerra in Ucraina presso il pubblico italiano:

a) Quelle che misurano la importanza/priorità di vari temi, le tipiche domande c.d. MIP (*Most Important Problem*) o MII (*Most Important Issues*). Sono incluse qui le domande che chiedono quali debbano essere le priorità per sé stessi (ad es. EB97.5), per il paese (ad es. EB97.5), per l’UE (ad es. EB98.1), per il Parlamento Europeo (ad es. EB97.3) e per il governo (es. Euromedia Research). Sono generalmente domande a risposta  multipla (offrendo tra 2 e 3 possibili scelte). I temi non fanno riferimento esplicitamente all’Ucraina, ma a tematiche più generali, come la situazione internazionale. 

b) Quelle che esplicitamente e direttamente chiedono la preoccupazione per la guerra in Ucraina.

c) Quelle che misurano la preoccupazione per le conseguenze della guerra (ad es. per la situazione economica o per il rischio di escalation sia geografica che di armamenti).

d) Quelle che misurano i sentimenti e le emozioni prevalenti in questo periodo. 

## Principali risultati 

* Maggioranze assolute superiori all'80% si dichiarano preoccupate della guerra in Ucraina. 

Ai primi di marzo 2022 (Euromedia) l’88% degli intervistati si dichiara molto o abbastanza preoccupato della guerra. Analoghe maggioranze trova Demos & Pi/Demetra a marzo 2022 (93%) e ad aprile 2022 (91%). Percentuali simili ottiene SWG tra marzo e aprile 2022. I trend disponibili più lunghi (quello EMG e quello IPSOS) rivelano una sostanziale stabilità nel tempo di questa preoccupazione. L’indagine continuata IPSOS, avviata con le domande poste tra il 15 e il 18 marzo 2022, riporta che l’86% degli intervistati si dichiari molto o abbastanza preoccupato. Il 18-19 ottobre 2022 tale percentuale è all’80% e, seppur a distanza di 4 mesi, la medesima percentuale è approssimativamente stabile nel tempo: nell'indagine del 21-23 febbraio 2023 il 79% degli intervistati si dichiara molto o abbastanza preoccupato per il conflitto russo-ucraino.

* I problemi economici e quelli ambientali preoccupano gli italiani molto di più di quelli legati all’Ucraina.

Questo effetto è in parte determinato dal formato della domanda. La preoccupazione per la guerra in Ucraina è molto maggiore quando agli intervistati viene chiesto questo, rispetto a quando la guerra è una tra molteplici preoccupazioni, tra le quali scegliere le due o tre ritenute prioritarie. Un esempio di questo effetto si trova comparando le risposte ad una domanda che misura la preoccupazione per la situazione internazionale rispetto alla guerra ai confini dell’Europa in due formati diversi. Il primo invita a sceglierne tre tra più di 10 problemi; il secondo chiede invece, per ogni problema, quanto preoccupato è l’intervistato (EB97.5  giugno-luglio 2022). Dovendo scegliere diversi problemi tra molti, solo il 12% degli italiani menziona la situazione internazionale come uno dei due temi più importanti per loro personalmente, mentre il 58% risponde che la guerra nelle vicinanze dell’UE è molto importante quando invitati ad indicare se, per loro, questo problema è importante. 
Nelle due domande poste da Euromedia Research tra marzo e maggio 2023, indaganti quali, tra una lista di temi, rappresentino il maggior problema per l'Italia, "La guerra che non presenta una via d’uscita" occupa rispettivamente il 4° posto a marzo e l'8° a maggio; "L'inflazione e l'aumento dei prezzi" occupa in ambedue le domande il primo posto, "Il cambiamento climatico e la precarietà del nostro territorio di fronte a grandi eventi atmosferici" il secondo posto nella domanda posta a maggio 2023.

* In entrambi i tipi di formulazione, la preoccupazione per la guerra è leggermente calata nel tempo (trends IPSOS ed EMG).

I trends EMG e IPSOS rivelano un andamento simile, con circa l’80% degli intervistati che si dichiarano preoccupati della guerra e della sua evoluzione, ma si ravvisa una leggera tendenza al calo del numero di persone preoccupate, nel caso della serie EMG a partire da aprile (con una leggera risalita a maggio) e nel caso IPSOS tra aprile e maggio 2022 con una ulteriore caduta a luglio 2022, una ripresa dopo il mese di agosto 2022 e un'ulteriore caduta a dicembre 2022. Il trend EMG non mostra questo calo perché si interrompe prima, finendo ad inizio giugno 2022.

* La guerrra preoccupa gli italiani soprattutto per le  sue possibili conseguenze economiche, piuttosto che per quelle politiche, militari o personali, anche se le risposte sono fortemente influenzate dal tipo di conseguenze indicate e dalla possibilità di sceglierne più d’una o solo una.

La domanda che più direttamente consente di comparare quali conseguenze della guerra sono più preoccupanti è stata posta da IPSOS che chiede quale aspetto – tra quelli economici, politici o umanitari – sia più preoccupante. Le conseguenze economiche sono sempre menzionate dalla maggioranza (relativa o assoluta), seguita da un terzo a un quarto di intervistati che menziona quelle belliche e da un decimo che riporta quelle umanitarie. Queste priorità sono confermate dalla domanda SWG nella quale il numero di persone preoccupate che “il quadro economico peggiori pesantemente" passa dal 51% del 9 marzo 2022 al l’86% del 23 marzo 2022. Circa un anno dopo, nella domanda SWG del 15-20 febbraio 2023, la medesima preoccupazione ritorna ai livelli iniziali: il 47% degli intervistati (la maggioranza relativa) si definisce preoccupato che "il quadro economico peggiori pesantemente", in quest'ultima domanda però il numero di opzioni tra cui scegliere è aumentato a 9 dalle iniziali 5. Le vittime, l’uso dell’arma nucleare e la possibilità che dopo l’Ucraina, la Russia invada altri paesi totalizzano percentuali nettamente inferiori. In alcune indagini dei primi due mesi, tuttavia, le preoccupazioni sul conflitto appaiono prevalenti rispetto a quelle economiche. Questo avviene *prima* dello scoppio del conflitto (ad es. l’indagine SWG del 16-18 febbraio 2022) o in isolati indagini nei primi mesi (ad es. l’indagine Euromedia, 27-28 aprile 2022).

* Tra gli aspetti economici che suscitano preoccupazione, vi sono l’aumento dei prezzi (indagini EMG), anche se la maggioranza l’attribuisce agli speculatori piuttosto che alla guerra (IPSOS, 14 marzo 2022). La maggioranza teme gli effetti sulla propria personale situazione economica (Noto sondaggi) o addirittura già ne sente gli effetti ad aprile 2022 (Noto sondaggi). 

[**APPENDICE**](https://github.com/LucianaFazio/Ucrania/blob/main/PDF_Appendice/II%20Preoccupazioni%20Ucraina%20v.6.pdf)

