#  LE CAUSE DELLA GUERRA: DI CHI È LA COLPA?

## Formulazione delle domande

L’esame delle cause della guerra nell’opinione degli intervistati è stato esaminato da almeno tre punti di vista: 

* Il primo è il contenuto della domanda. Alcune domande cercano di accertare le responsabilità della guerra, di chi è insomma la colpa (il c.d. *blaming*) mentre altre esplorano le motivazioni o cause della guerra. Rilevano qui le opinioni degli intervistati sulle responsabilità rispettive dei due schieramenti circa l’inizio e la persistenza della guerra, nonché quelle che approfondiscono le motivazioni o cause prevalenti del conflitto.

* Un secondo aspetto attiene al formato della domanda. Fondamentalmente è possibile distinguere due tipi di formati delle domande che esplorano questi temi. Da un lato, vi sono domande che chiedono direttamente di indicare di chi è la colpa o la responsabilità del conflitto tra le due parti. Dall’altro vi sono domande che invece elencano o suggeriscono una serie di motivazioni e/o spiegazioni possibili della guerra. Non sorprendentemente, i due tipi di domande producono risultati sensibilmente diversi. 

* Infine, un terzo aspetto è quello della comparabilità delle domande nel tempo o nello spazio. Gran parte delle domande sono state poste solo occasionalmente dai vari istituti di sondaggio, rendendo quindi difficile una valutazione dell’andamento dei giudizi degli italiani nel tempo, con una sola eccezione, la domanda IPSOS sulle cause del conflitto, che è stata reiterata per diversi mesi. Vi è anche un caso in cui la domanda sulla responsabilità è stata posta in diversi paesi, consentendo una valutazione della posizione italiana con quella di altri paesi.

## Principali risultati 

* Maggioranze assolute di circa due terzi degli intervistati indicano la Russia come principale responsabile del conflitto.

Diverse domande hanno esplorato il tema delle responsabilità della guerra. Tra febbraio e marzo 2022 circa l’80% degli intervistati SWG ritiene l’attacco della Russia all’Ucraina “inaccettabile, da condannare severamente” e il 71% degli intervistati SWG del 21-25 marzo 2022 esprime una “condanna totale dell’attacco.” Similmente tra marzo e aprile 2022 il 77% degli intervistati da Demetra considera l’attacco grave e ingiustificato.

Il *wording* della domanda sembra avere un leggero effetto sulle risposte. Quando la domanda usa termini più neutrali rispetto a “colpa” e “condanna”, parlando ad esempio di “motivazioni” (ad es. Euromedia ed EMG) o di “ragioni,” le percentuali di intervistati che puntano il dito sulla Russia restano elevate, ma sono leggermente inferiori a quelle appena citate. Ad esempio, la percentuale di intervistati che ritiene prevalenti le motivazioni (o le ragioni) ucraine scende al 57%-60% in una serie di domande EMG ed Euromedia Research.

* Quando la domanda sollecita la risposta ad una più articolata serie di motivazioni, il giudizio degli italiani si fa più sfumato e meno netta emerge la responsabilità esclusiva della Russia.

Nel periodo compreso tra il 23 e il 28 marzo 2022 Termometro Politico ed EMG hanno posto due domande più articolate di quelle esaminate sinora, elencando tra le alternative di risposta considerazioni diverse. Ad esempio, Termometro politico nell’invitare a dare un giudizio sull’intervento militare della Russia in Ucraina offriva la scelta tra la seguente serie di motivazioni: “È stato un atto molto grave, una prevaricazione intollerabile verso uno stato sovrano;” “È stato un atto avventato e sbagliato, secondo me, ma se rimane limitato al Donbass non è così grave;” “È stata una mossa comprensibile, se rimane limitata al Donbass, si è trattato di un giusto atto di protezione verso la minoranza russa;” e “Ha fatto bene, l'Ucraina rischia di diventare un fantoccio occidentale, dovrebbe tornare sotto l'egida di Mosca.” Non sorprendentemente, l’opportunità di offrire un giudizio più articolato riduce al 39% la percentuale di intervistati che condanna recisamente l’intervento militare come “atto molto grave.” Il resto degli italiani esprime giudizi più sfumati, con un 14% dei quali è decisamente apologetico nei confronti della Russia, approvandone l’operato. L’indagine EMG del 28 marzo 2022 pone all’intervistato delle alternative di ancor più ampia portata e anche qui non più del 20% aderisce ad una posizione di condanna decisa dell’operato russo, sottoscrivendo che “È una guerra tra due Paesi, in cui uno ha illegittimamente aggredito l'altro.” Il resto degli intervistati preferisce ascrivere il conflitto ad uno scontro di più ampia portata. 

Quanto fino a qui osservato è confermato da due domande del Termometro Politico: con la prima (15-17 novembre 2022) viene indagata in maniera più articolata l'esistenza di eventuali agenti esterni determinanti nell'origine del conflitto, e si osserva come solo l'11% degli intervistati ritenga che la guerra ci sarebbe stata ugualmente e avrebbe avuto un andamento simile a quello attuale; la seconda domanda (14-16 febbraio 2023) sollecita nella risposta una più articolata motivazione sulle responsabilità della guerra, ciò che si delinea è che il giudizio degli italiani si fa più sfumato ed emerge meno nettamente la responsabitlità unica della Russia: il 47% degl intervistati addita in Putin e nella Russia come i responsabili del conflitto. Infine, la domanda IPSOS sulle cause della guerra – che riprende la nota tesi avanzata dai neorealisti circa le responsabilità della NATO nell’aver determinato le reazioni russe – offre anch’essa una serie articolata di ragioni della guerra, quali “La minaccia della NATO giustifica l’invasione Russa dell’Ucraina;” “La Nato minaccia la Russia, ma ciò non giustifica l’invasione;” e “La Russia ha solo cercato un pretesto e non ha giustificazioni per l’invasione dell’Ucraina.” E anche in questo caso aderiscono alla tesi della responsabilità esclusiva della guerra percentuali mai molto superiori al 50% di intervistati.

* Maggioranze decrescenti nel tempo tendono ad attribuire la colpa della guerra alla Russia, allo stesso tempo, maggioranze crescenti tendono a non voler rispondere, ovvero dichiarano di non sapere rispondere. A livello europeo l'Italia è il paese dove si registrano percentuali minori tra coloro che attribuiscono le colpe alla Russia. 

Una prima, ancorché circoscritta, serie temporale è quella di Euromedia Research ed EMG tra marzo e maggio 2022 che evidenzia come il fronte di coloro che ritengano prevalenti le motivazioni ucraine cresca leggermente nel tempo (dal 57% di marzo '22 al 61% di maggio '22). La più lunga serie temporale IPSOS sulle “cause del conflitto” mostra un leggero declino di coloro che ritengono che “La Russia ha solo cercato un pretesto e non ha giustificazioni per l’invasione dell’Ucraina,” in direzione di una maggiore incertezza cica l’attribuzione delle colpe. A marzo (28-30 marzo 2022) la percentuale di coloro che ritrovavano nella Russia la responsabile unica del conflitto erano il 49%, mentre un altro 28% riteneva che la NATO minacciasse la Russia ma che ciò non giustificasse l’invasione, e un residuo 6% era composto da coloro che ritrovavano invece nella minaccia della NATO una giustificazione dell’invasione. A settembre dello stesso anno il fronte di coloro che ritenevano la Russia l’unica responsabile scende al 42%, mentre cresce dal 17% al 25% in sei mesi la percentuale di coloro che non sanno o preferiscono non rispondere.

Tra l’8 e l’11 marzo 2022 SWG-Euroskopia ha chiesto ai cittadini di 6 paesi europei se l’attacco russo all’Ucraina fosse inaccettabile, inaccettabile ma comprensibile o accettabile. L’Italia è al penultimo posto (seguita solo dalla Grecia) con il 71% che lo ritiene inaccettabile (a fronte del 60% dei greci) e il 19% inaccettabile ma comprensibile. Questa percentuale è inferiore a quella di Olanda (88% inaccettabile), Spagna (86%), Germania (82%) e Francia (78%). Alla domanda “Le autorità russe sono le principali responsabili della situazione attuale” posta nel Flash Eurobarometro 506 del 14-20 aprile 2022 il 73% degli italiani hanno risposto di essere d’accordo. Questo pone gli italiani al 18° posto, dopo tutti i principali paesi europei occidentali e al di sotto della media europea del 78%.

* Maggioranze assolute condannano l'attacco della Russia all'Ucraina in maniera totale o parziale. Indagando le risposte degli intervistati e la risposta dell'Ucraina nel corso dei mesi queste maggioranze tendono a declinare. 

Nel sondaggio SWG del 23-25 marzo 2022 si osserva che l’82% degli intervistati condanna l’attacco nei confronti dell’Ucraina (71% totalmente e l’11% parzialmente), in linea con le rilevazioni SWG del 25-28 febbraio 2022 e del 23-28 marzo 2022 dove, sullo stesso numero di intervistati (800), il 79% in ambedue i rilevamenti ritiene che l’attacco sia inaccettabile e da condannare severamente, e in linea altresì – anche se leggermente in calo – con i dati di Demetra dell’11-12 aprile dello stesso anno: il 76% degli intervistati ritengono grave e ingiustificata la scelta della Russia di iniziare l’intervento militare. Valutando invece gli schieramenti degli intervistati si osserva che solo il 58% di questi si dichiara apertamente con l’Ucraina (EMG 16 aprile 2022), solo il 64% spera che Putin perda la guerra mentre il 26% sono indecisi (SWG 27 aprile-2 maggio 2022), infine, ad ottobre (Euromedia Research 26 ottobre 2022), soltanto il 36% riteneva ancora che l’Ucraina dovesse resistere a tutti i costi, la maggioranza (quasi assoluta) si schierava su posizioni di concessioni alla Russia (49%).

[**APPENDICE**](https://github.com/LucianaFazio/Ucrania/blob/main/PDF_Appendice/III.%20Le%20cause%20della%20guerra_v.5.pdf)
