# L’ANDAMENTO DELLA GUERRA: COME FINIRÀ?

## Formulazione delle domande

L’esame dell’andamento della guerra nell’opinione degli intervistati è stato condotto da molteplici punti di vista. Possiamo distinguere le domande rivolte agli intervistati su questi temi prevalentemente sulla base del contenuto della domanda e, all’interno di classi divise per contenuto, è possibile altresì distinguere le domande in funzione del formato dell’indagine.

* Il contenuto della domanda diversifica sensibilmente i sondaggi tra di loro. Alcune domande cercano di accertare il vincitore attuale e futuro del conflitto, mentre altre domande indagano i pericoli avvertiti dagli intervistati circa possibili escalation, ovvero le considerazioni circa la durata effettiva della guerra o, ancora le condizioni per porvi fine.

* Un secondo aspetto attiene al formato della domanda e ciò rileva particolarmente all’interno di ogni classe divisa per contenuto. Ad esempio, quando si indaga su chi sono i vincitori attuali e quelli presunti in futuro, si osservano differenze significative a seconda di come la domanda venga posta. Ciò è vero anche quando si esplorano le preoccupazioni di escalation: Il *wording* nel sondaggio sembra avere un effetto sulle risposte.

* Infine, un terzo aspetto è quello della comparabilità delle domande nel tempo. Sebbene la maggior parte delle domande siano state poste solo *una tantum* dai vari istituti di sondaggio – il che complica un’eventuale analisi dell’andamento dell’opinione pubblica degli italiani nel tempo –  si ritrovano, soprattutto circa il vincitore del conflitto, serie continuative nel tempo.

## Principali risultati

### Esito del conflitto: chi vincerà?

*	Maggioranze sensibilmente diverse caratterizzano le risposte alle domande su chi vincerà la guerra e su chi la stia attualmente vincendo.

Diverse domande hanno esplorato il tema del vincitore – presunto e attuale – del conflitto in corso. Ad Aprile 2022 il 22% degli intervistati di Noto Sondaggi ritiene che la Russia di Putin stia attualmente vincendo il conflitto e il 26% degli intervistati, sempre di Noto Sondaggi, conferma anche che la Russia vincerà la guerra. La medesima valutazione non può essere fatta però per il fronte ucraino: il 47% degli intervistati crede che l’Ucraina stia attualmente vincendo, ma soltanto il 28% crede che vincerà. Logicamente, si osservano variazioni importanti anche nel gruppo degli indecisi: coloro che non sanno chi, tra Russia e Ucraina, stia vincendo momentaneamente il conflitto sono circa il 30%, chi invece non sa esprimersi su chi vincerà il conflitto sono quasi il 50%. 

Questa valutazione può essere riproposta per Maggio 2022 nei sondaggi Ipsos, EMG, Demopolis. Rimane stabile la percentuale di coloro che credono che la Russia stia vincendo (23%) ma diminuisce il numero di coloro che credono che Putin vincerà la guerra (12%). Si osserva poi che la percentuale degli intervistati che ritengono l’Ucraina vincente nel momento in cui viene posta la domanda è sempre maggiore rispetto alla percentuale di chi ritiene che l’Ucraina vincerà la guerra (47%–28% ad Aprile, 28%–20% a Maggio 2022).

* Maggioranze decrescenti nel tempo credono che la Russia di Putin vincerà il conflitto, contemporaneamente maggioranze crescenti nel tempo si dichiarano indecise sul possibile vincitore o preferiscono non indicarne alcuno. 

A Marzo 2022 il 52% degli intervistati per il Termometro politico sosteneva che la Russia di Putin avrebbe vinto la guerra (sebbene il 24% di questi ritenevano altresì che all’occupazione russa l’Ucraina avrebbe resistito duramente), il 37% riteneva invece che sarebbe stata l’Ucraina a vincere e solo il 10% preferiva non rispondere o non sapeva. Sempre a Marzo 2022: per il 58% degli intervistati Ipsos la Russia avrebbe vinto la guerra, solamente per il 13% a vincere sarebbe stata l’Ucraina, mentre il numero di coloro che non sapevano o non volevano esprimersi si attestava intorno al 20%. Ad Aprile 2022, secondo Noto Sondaggi, il fronte di coloro che ritenevano che la Russia avrebbe vinto la guerra si assottiglia al 26%, similmente anche il numero di coloro che ritenevano il fronte ucraino come prossimo vincitore si attesta attorno a percentuali simili (28%), a crescere sensibilmente, invece, è il gruppo di chi non sa o non vuole indicare un netto vincitore: il 46% degli intervistati, infatti, preferisce non esprimersi. 

Si osservi poi che a Maggio 2022 (IPSOS) il numero di coloro che ritenevano la Russia come futura vincitrice del conflitto crolla al 12%, similmente, anche chi riteneva l’Ucraina vincitrice scende al 20%, la terza opzione è preferita dal 68% degli intervistati e, di questi, il 12% non sa o non vuole indicare, ma il 56% indica “nessuno” come futuro vincitore. Questi dati sono parzialmente riscontrabili nella domanda del Termometro Politico del febbraio 2023 (21-23 febbraio 2023): solo il 19% degli intervistati rimane dell'idea che la Russia avanzerà conquistando terreno e/o costringendo l'Ucraina a una resa, il 12% ritiene invece che sarà l'Ucraina ad avanzare e a "scacciare i Russi", il 43% invece ritiene che la guerra proseguirà con uno stallo militare tra le due parti. 

*	Maggioranze decrescenti nel tempo ritengono che la Russia o l'Ucraina stiano vincendo la guerra, allo stesso tempo ad aumentare gradualmente sono il numero degli indecisi.

A Marzo 2022 il 28% degli intervistati Ipsos credeva che la Russia stesse vincendo la guerra, mentre il 39% riteneva che l’Ucraina fosse in vantaggio e soltanto il 33% non sapeva o non voleva indicare un vincitore. A Maggio alla stessa domanda il 23% degli intervistati EMG indicava la Russia di Putin come forza militarmente in vantaggio sull’altro schieramento, subendo nel corso di due mesi una perdita in termini percentuali di 5 punti. Una riduzione più significativa si registrava invece sull’altro lato dello schieramento: solo il 28% riteneva l’Ucraina di Zelensky in vantaggio, facendo rilevare un calo in termini percentuali di 11 punti rispetto ai precedenti 39. Se ne trae che l’unica opzione che ha visto crescere le proprie percentuali sia la terza: chi non sapeva o non voleva esporsi passa dal 33% al 49% (+16%). Nel giro di due mesi quasi un intervistato su due non sapeva o non voleva indicare quale schieramento stesse vincendo il conflitto nel momento in cui la domanda gli veniva posta. 

*	Maggioranze crescenti nel tempo prevedono la conclusione del conflitto mediante il ricorso a una soluzione diplomatica o comunque con un compromesso tra le parti, contemporaneamente cala nel tempo il numero degli indecisi e di coloro che preferiscono non rispondere

Dalla serie EMG svoltasi a Maggio 2022 si evince che maggioranze crescenti prospettano il ricorso a un compromesso tra le parti. Se a metà Maggio il 44% degli intervistati EMG prevede il ricorso a una soluzione diplomatica per porre fine al conflitto bellico, alla fine di Maggio il 57% del campione si augura un compromesso che possa mettere d’accordo i diversi schieramenti. È interessante osservare come, allo stesso tempo, a decrescere non sia il numero di coloro che sostengono convintamente la vittoria militare e schiacciante di uno dei due schieramenti – Russo o Ucraino che sia – bensì il fronte degli indecisi: il 17-19 Maggio 2022 il 42% degli intervistati EMG preferivano non rispondere alla domanda. A fine maggio la stessa opzione è scelta solamente dal 24% degli intervistati. Si rinforza, anche se in misura ridotta e dopo un breve e leggero declino, all’opposto, il fronte di chi crede che la guerra si concluderà con la vittoria di una delle due parti. A distanza di mesi (Ipsos, 10-11 gennaio 2023) l'opzione diplomatica e di compromesso tende ad essere favorita da maggioranze relative simili a quelle iniziali: il 45% degli intervistati ritiene che il conflitto terminerà con un accordo di pace, resta pressocché costante invece la percentuale di chi ritiene che il conflitto terminerà con la vittoria di una delle due parti (17%).

### Escalation

#### *Escalation: Rischio guerra nucleare*

* La preoccupazione per una possibile escalation nucleare diminuisce nel tempo fino ad ottobre 2022. Il *wording* sembra avere un duplice effetto sulle risposte: vengono rilevate significative differenze a seconda che venga nominata direttamente o meno l’espressione *“guerra atomica”*, ovvero se ad essere indagate sono le preoccupazioni o le probabilità che tale evento avvenga.

Diverse domande hanno esplorato il tema dell’eventualità di una escalation nucleare. A Marzo 2022 il 72% degli intervistati Euromedia Research ritiene che la possibilità di una escalation nucleare sia avverabile, similmente ad Aprile 2022, il 68% degli intervistati della serie EMG (5 sondaggi ripetuti nell’arco di due mesi) temevano che la guerra potesse degenerare in un conflitto nucleare, a Maggio dello stesso anno la stessa percentuale si riduce attestandosi intorno al 60%. 

La serie continuata IPSOS conferma e rafforza quanto detto: a Marzo 2022 il 31% degli intervistati ritenevano probabile (molto e abbastanza) il ricorso ad armi nucleari. A Settembre dello stesso anno il medesimo fronte era invece composto dal 19% del campione. Contemporaneamente, se a Marzo il 45% degli intervistati ritenevano poco o per nulla probabile un conflitto nucleare, a Settembre gli stessi pesavano per il 56% nel campione analizzato. 

Si osservi però come da Ottobre la preoccupazione per un conflitto nucleare ritorni nuovamente predominante nell’opinione pubblica: il 30% degli intervistati l’11 e il 12 Ottobre 2022 dichiarano molto o abbastanza probabile un ricorso ad armi nucleari (valori identici a quelli di Marzo), allo stesso tempo anche il fronte di chi crede poco o per nulla probabile un conflitto nucleare ritorna ai valori di Marzo attestandosi attorno al 40% degli intervistati.

Il *wording* sembra avere un leggero effetto sulle risposte: quando la domanda usa il termine “bomba atomica”, ovvero “guerra atomica”, le percentuali di intervistati che si dimostrano preoccupati di un eventuale escalation si riduce rispetto a quando si usa “conflitto nucleare”: ad Aprile il 34% e ad Ottobre il 43% degli intervistati del Termometro Politico ritengono probabile o possibile una guerra nucleare.

Quando si indaga la preoccupazione che l'evento atomico avvenga e non più la sua probabilità di accadimento, robuste maggioranze assolute si dichiarano preoccupate per un'eventuale escalation nucleare. Ciò è ravvisabile non solo nella serie continuata EMG condotta tra aprile e maggio 2022, ma anche nelle domande poste a febbraio 2023: per EMG (27 febbraio 2023) il 69% degli intervistati si dichiara molto o abbastanza preoccupato per un'eventuale escalation nucleare, per Demopolis (21-22 febbraio 2023) il 68% degli intervistati conferma tale preoccupazione. 

#### *Escalation: Terza guerra mondiale e No fly zone*

* Anche la preoccupazione per una escalation su scala mondiale del conflitto decresce nel tempo: maggioranze gradualmente più consistenti si convincono che il conflitto sarà limitato dei due paesi. 

A Marzo 2022 solo il 29% degli intervistati IPSOS ritiene che il conflitto non travalicherà i confini dei due paesi coinvolti, ad Aprile 2022 circa il 40% degli intervistati DemosPi & Demetra e EMG si confermano convinti che il conflitto non coinvolgerà nessun altro paese al di fuori di Ucraina e Russia. Si segnala altresì che nell’eventualità di una *no fly zone* a Marzo dello stesso anno per l’83% degli intervistati Demopolis ritiene che si correrebbe il pericolo di un allargamento della guerra su scala mondiale.

Questo trend è confermato dalla serie continuata IPSOS che da marzo a febbraio 2023 indaga l’opinione pubblica circa i rischi di una degenerazione del conflitto: se a marzo 2022 il 24% degli intervistati ritiene plausibile che il conflitto russo-ucraino degeneri in una guerra mondiale, a settembre dello stesso anno la medesima opinione è condivisa solo dall’11% della popolazione. Parimenti: a marzo 2022 il 26% degli intervistati ritiene che il conflitto rimarrà confinato nei confini dei due paesi belligeranti, sei mesi dopo la stessa posizione è sostenuta da ben il 39% degli intervistati. Tuttavia, ad ottobre 2022 si osservano valori contrastanti con i trend registrati durante i 9 mesi precedenti: le percentuali delle rispettive posizioni si riavvicinano alle stime di Marzo: solo il 26% degli intervistati il 5-6 ottobre 2022 ritiene che il conflitto resterà isolato nei confini dei due paesi in guerra; il 20% degli intervistati l’11 e il 12 ottobre ritengono invece di nuovo plausibile un conflitto su scala mondiale. Infine, a febbraio 2023 i parametri si ristabilizzano sul trend osservato nei mesi precedenti: decresce nuovamente il numero di chi sostiene che il conflitto degenererà in una guerra mondiale (16%), parimenti cresce di molto la percentuale di chi, all'opposto, ritiene che il conflitto resterà limitato tra Russia e Ucraina (31%). Si osservi, a conclusione di ciò, che nella serie IPSOS qui indagata tra marzo 2022 e febbraio 2023, la percentuale di chi ritiene che il conflitto si estenderà, ma nei soli limiti dell’Europa orientale, resta pressocché costante nel tempo (25%-33% degli intervistati).

### A quali condizioni finire il conflitto e quale possibilità di negoziati

* Maggioranze solide nel tempo ritengono che per porre fine al conflitto l’Ucraina debba fare delle concessioni alla Russia: il compromesso rimane costantemente l’opzione favorita dagli intervistati.

Molteplici domande indagano l’opinione degli intervistati circa le condizioni con cui porre termine alla guerra in corso. Resta costante la percentuale di coloro che, nel corso del tempo e a domanda diretta, rispondono che l’unico metodo per concludere il conflitto sia la resa dell’Ucraina nei confronti della Russia. Il 38% degli intervistati Euromedia Research a Marzo 2022 ritiene che l’Ucraina debba arrendersi (nonostante il 76% degli intervistati Noto Sondaggi dello stesso mese ritengano che la maggiore responsabilità sia proprio della Russia), il 43% degli intervistati Ipsos a Marzo 2022 condivide questa opinione, il 52% degli intervistati SWG a Maggio dello stesso anno crede che il conflitto si possa concludere o con la sconfitta totale Ucraina (6%) o con il controllo dei territori occupati dalla Russia (46%). Addirittura, il 74% degli intervistati del Termometro Politica lo stesso mese ritengono che sarebbe accettabile un accordo di pace che includesse l'annessione da parte della Russia di tutto o parte del territorio ucraino occupato. 

Proprio il tema della cessione di territori ucraini alla Russia incontra nel tempo percentuali significative, prossime alla maggiorana relativa: solo il 10% del campione di SWG di Aprile 2022 dichiara che l’Ucraina *non* debba concedere nulla alla Russia, il 40% dei soggetti ascoltati dal Proger IndexResearch a Maggio 2022 credono che l’Ucraina debba accettare una qualche forma di rinuncia territoriale (il 37% è contrario il 23% non sa o non indica). Il 46% degli intervistati dal Termometro Politico di Giugno 2022 ritengono che non costituisca un precedente pericoloso la cessione di territori occupati, il 49% del campione di Euromedia Research ad Ottobre 2022 crede che l’Ucraina debba fare delle concessioni per accelerare il processo di pace. Infine, il 44% degli intervistati Tecné 11-13 febbraio 2023 ritengono che sia da valutare l'ipotesi delle concessioni territoriali in cambio della pace, similmente il 54% del campione Proger IndexResearch (22 marzo 2023) ritiene che debbano essere fatte delle concessioni al fine di fermare la guerra.

Allo stesso tempo maggioranze rilevanti si augurano un compromesso tra le parti al fine di porre termine, nel minor tempo possibile, al conflitto in atto. Ad Aprile 2022 il 56% degli intervistati di Euromedia Research credono che il compromesso tra le parti sia l’obiettivo sul quale puntare, sempre ad Aprile il 55% del campione di EMG dichiara che l’Europa dovrebbe in tutti modi promuovere la trattiva diplomatica, la stessa opzione è favorita dal 62% degli intervistati Ipsos a Maggio 2022, sempre a Maggio il 62% degli intervistati EMG credono che una soluzione diplomatica sia possibile (in tempi lunghi e in tempi brevi). Ad ottobre 2022 il 54% del campione ascoltato dal Proger IndexResearch auspicano un compromesso mediato tra Putin e le forze politico – istituzionali dell’Occidente, infine anche a febbraio 2023 il 60% degli intervistati da SWG ritiene che il conflitto si concluderà per via negoziale.

### Durata conflitto

*	Fatte eccezione per i primi mesi della guerra, si osservano maggioranze stabili nel corso del tempo nella distribuzione delle preferenze circa la durata del conflitto, con effetti interessanti dovuti al numero di opzioni a disposizione da parte degli intervistati.

A Marzo 2022 il 21% degli intervistati EMG riteneva che il conflitto si sarebbe concluso nel giro di poche settimane, a Maggio dello stesso anno tale percentuale si riduce a cifre sempre inferiori al 10% degli intervistati, fino a toccare la percentuale minima nel sondaggio del 12 Maggio 2022: 3%.

È utile osservare altresì come, nell’eventualità in cui agli intervistati siano date più opzioni di scelta la percentuale di coloro che non sa o non si vuole esprimere sia sensibilmente contenuta: nel sondaggio dell’11-12 aprile 2022 di Demos&Pi Demetra con cinque opzioni solo il 9% non prende una posizione; nei sondaggi EMG dal 5 al 26 maggio 2022 con tre opzioni preferibili, circa il 30% degli intervistati preferisce non esporsi. Tali effetti tendono però a ridursi con il passare dei mesi: i sondaggi posti ad inizio 2023 confermano questo trend.

*	Maggioranze crescenti nel tempo ritengono che il conflitto durerà qualche anno. 

Una serie IPSOS indaga le opinioni degli intervistati da marzo ad ottobre 2022: se a marzo il 24% del campione ritiene che il conflitto durerà un anno o più, ad ottobre la stessa opinione è sostenuta da 36% degli intervistati, consequenzialmente chi crede che il conflitto durerà solo alcuni mesi progressivamente si riduce: dal 46% del campione a 34%.

Infine, nei sondaggi del 2023 si osservano maggioranze assolute e stabili nel tempo che ritengono che il conflitto durerà ancora diversi mesi/anni: il 61% degli intervistati IPSOS il 21-23 febbraio 2023 ritiene che il conflitto durerà circa un anno o diversi anni, il 75% degli intervistati Euromedia Research il 21 febbraio 2023 vedono "lontana" la fine del conflitto.


[Appendice](https://github.com/LucianaFazio/Ucrania/blob/main/PDF_Appendice/IV.%20La%20guerra%20e%20il%20suo%20andamento%20v.4.pdf)
