# COSA DOBBIAMO/POSSIAMO FARE NOI?

## Formulazione delle domande

Il tema delle sanzioni (V.2) e dell’invio delle armi (V.1), le due principali forme di sostegno date dalla comunità occidentale all’Ucraina, rappresentano tra i temi più frequentemente esplorati nel corso del tempo e mostra che le variazioni nel sostegno sono fortemente influenzate dalla formulazione delle domande. Sebbene solo pochi istituti di sondaggio abbiano avuto la costanza di sottoporre domande identiche periodicamente nel tempo agli intervistati (le due eccezioni sono rappresentate da IPSOS e EMG), la comparazione dei (pochi) dati comparati nel tempo e dei (molti) modi in cui la domanda è stata chiesta mostrano chiaramente che gli ampi margini di variazione nelle percentuali di contrari, oscillando le percentuali di favorevoli rilevate dai due istituti di più di 20 punti percentuali, non sono tanto dovute ad una reazione agli eventi in Ucraina, quanto piuttosto a specifiche variazioni nel modo in cui sono formulate le domande e il loro formato.

Contemporaneamente ai due principali temi indagati, circa le azioni che possono e non possono essere messe in campo direttamente a sostegno di uno o dell’altro schieramento, sono state poste altresì domande relative il diretto intervento militare (V.3), l’ingresso nella NATO e nell’UE da parte dell’Ucraina (V.4), l’aumento delle spese militari (V.5) nonché le considerazioni circa l’istituzione dell’esercito europeo (V.6). 
In funzione di ciò è utile osservare come ciascun tema può essere analizzato separatamente dagli altri, studiando, pertanto, le intenzioni degli intervistati circa ogni tematica richiesta; ovvero, può essere utile osservarne una dimensione complessiva, centrata sulle azioni concrete e simboliche che gli intervistati sentono di voler (o non voler) complessivamente fare nei confronti dell’Ucraina. 
Il *Wording* sembrerebbe assumere una certa significatività soprattutto sui temi che non implicano azioni concrete o dirette sulla popolazione italiana, come, ad esempio, l’istituzione di un esercito (unico) europeo. 
Infine, le domande comparate tra più paesi dell’Unione Europea hanno un corrispettivo prevalentemente nell’analisi dei primi due paragrafi e nel quinto.

## Principali risultati

### Inviare Armi

Nell’insieme, sulla base dei sondaggi disponibili, il 40% degli italiani si dichiara favorevole all’invio di armi, ma con un ampio campo di variazione, che va da un minimo del 23% di italiani che il 10 ottobre 2022 ritengono “giusto continuare a inviare armi all’Ucraina” (indagine EMG), ad un massimo del 59% che il 20 aprile 2022 risponde di essere d’accordo con il “finanziamento dell'acquisto e fornitura di equipaggiamento militare all'Ucraina” (indagine Flash Eurobarometro). Il contenuto della domanda, il suo formato e le alternative di risposta hanno tutti un effetto sulle percentuali di favorevoli e contrari. Ad esempio, le percentuali di sostenitori dell’invio delle armi variano a seconda che si chieda se si sia “favorevoli,” se si sia d’accordo” o se sia “giusto” inviare armi. Al netto della formulazione delle domande, meno persone ritengono “giusto” l’invio delle armi (il 33% in media), rispetto a quanti sono “d’accordo” (il 46% in media) con quelli favorevoli che si collocano tra questi due estremi (38% in media). Questo effetto, ben noto in letteratura, e dovuto alla pressione sociale verso il consenso alle politiche del governo, comunque non altera il risultato complessivo.

Analogamente, la natura e combinazione delle alternative di risposta ha importanza. Un esempio è rappresentato dalle sistematiche differenze di percentuali tra EMG e IPSOS, dovute al fatto che IPSOS, diversamente dalla maggior parte degli istituti di sondaggio italiani, ha sollecitato l’opinione degli intervistati sull’invio delle armi offrendo loro una molteplicità di strategie alternative fra le quali scegliere, alcune delle quali non mutuamente esclusive.  Non solo, ma le alternative offerte sono cambiate nel corso del tempo. Per cui, ad esempio, la crescita dei favorevoli all’invio di armi di 6-7 punti percentuali tra il 12 e il 16-18 maggio ed un ulteriore aumento, di maggiore entità, tra la metà e la fine luglio nel trend IPSOS sono entrambi da ricondurre alla variazione nella formulazione delle alternative di scelta, piuttosto che a reali spostamenti del clima di opinione. Costringendo infatti chi era favorevole sia all’invio delle armi che alle sanzioni contro la Russia a scegliere una sola di queste soluzioni, un gruppo di costoro optava per le armi rispetto alle sanzioni, producendo un aumento dei favorevoli all’invio di armi (e la correlativa diminuzione del sostegno per le sanzioni). Analogamente, l'aumento del favore all’invio delle armi a partire da luglio 2022 è dovuto al fatto che, da quella data, scompare l'opzione delle sanzioni, mentre tre delle quattro alternative offerte agli intervistati prevedono la fornitura di armi, anche se in quantità diverse, e la quarta soluzione è quella diplomatica. In ogni caso, anche l'effetto del formato della domanda non modifica il fatto che non si ha una maggioranza assoluta di italiani favorevoli all’invio di armi (la formulazione IPSOS semplicemente deprime il già basso entusiasmo), ma semmai evidenzia che, per una parte degli italiani, armi e sanzioni non erano strategie alternative, ma due approcci da utilizzare in combinazione.

#### Gli Italiani e il sostegno all’invio delle armi

* I dati indicano con chiarezza che la maggioranza degli italiani è contraria all'invio di armi all'Ucraina, con percentuali di favorevoli mai superiori al 40% e tali percentuali restano stabili nel tempo.

*	Gli intervistati nel rispondere sono sensibili agli argomenti e temi evidenziati nelle domande. Le risposte variano a seconda del modo in cui si presenta la natura delle armi inviate e gli attori che le inviano all’Ucraina.

Il riferimento al tipo di armamenti – pesanti o offensive e leggere o difensive – inviati all’Ucraina e il contributo che può avere tale riferimento nell’aumentare o diminuire il sostegno ha suscitato qualche discussione tra gli addetti ai lavori. Una analisi dei dati disponibili sembra indicare che tale riferimento non ha un effetto significativo sugli intervistati, né in una direzione né nell’altra. Due domande (tutte da Euromedia) che specificano quali armi dovrebbero essere inviate (missili, cingolati, artiglieria pesante, ecc.) ottengono percentuali di favorevoli in media con le domande che invece non specificano la natura delle armi da inviare (rispettivamente il 38% il 25 maggio e il 41% il 28 aprile). Queste percentuali sono leggermente superiori a quella ottenuta il 3 maggio 2022 dall’EMG, in cui il 28% era d’accordo con l’invio di “armi pesanti” all’Ucraina, in leggerissimo calo rispetto al 30% di favorevoli della rilevazione precedente, ma che viene poi recuperata dalla rilevazione successiva del 10 maggio. 

Leggermente diverso è il discorso su chi deve inviare le armi; se cioè il riferimento esplicito al governo italiano o ad altri attori, quali la NATO o l’UE, abbia un qualche effetto. In questo caso si registra un leggero aumento del sostegno in assenza di un esplicito riferimento all’Italia. La EMG il 30 maggio 2022 ha chiesto se la NATO (non l’Italia) dovese inviare “armi più pesanti di quelle inviate finora (per esempio aerei da guerra)” e in questo caso la percentuale di italiani favorevoli scende al 25% (a fronte di un 44% di contrari e di un 31% di persone che non sanno o non rispondono). Poiché in questa domanda è presente anche un riferimento alle armi pesanti, può essere utile vedere se le cose cambiano quando questa informazione non è inclusa nella domanda. Una indagine della Bertelsmann Foundation aiuta a rispondere: il riferimento all’Italia, piuttosto che all’UE, riduce leggermente il favore all’invio di armi, che passa dal 42% degli italiani a favore dell’invio delle armi da parte dell’UE, al 39% di quelli che lo pensano se è l’Italia a farlo. Il riferimento all’UE potrebbe contribuire a spiegare (insieme all’anodino riferimento al “finanziamento di equipaggiamenti militari”) perché nel Flash Eurobarometer di aprile il 59% si dichiara favorevole al “finanziamento dell’acquisto e fornitura di equipaggiamento militare all’Ucraina,” la percentuale in assoluto più alta di favorevoli all’invio delle armi, mai raggiunta in Italia in ogni periodo. 

Anche il riferimento alla NATO sembra avere un qualche effetto. Nel maggio 2022 IPSOS propose due formulazioni diverse della stessa domanda, a breve distanza di tempo, in una delle quali si chiedeva se “è giusto che l’Italia e la Nato continuino ad inviare armamenti all’Ucraina” (9 maggio 2022) mentre nella seconda se “è giusto che l’Italia invii armamenti all’Ucraina” (2 maggio 2022). In questo caso, la differenza è minima. Il 40% è favorevole a che l’Italia lo faccia e il 41% quando anche la NATO è menzionata. Analogamente, quando il 30 maggio ad una domanda EMG che chiedeva “cosa dovrebbe rispondere la Nato” a “Kiev [che] chiede armi più pesanti di quelle inviate finora (per esempio aerei da guerra)” solo il 25% era favorevole a questa richiesta, una percentuale non dissimile da quella di precedenti e successive indagini dell’EMG. Tuttavia, poiché la prima domanda IPSOS include l’Italia con la NATO e la seconda ha anche un riferimento alle armi pesanti, il LAPS dell’Università di Siena ha cercato di chiarire il ruolo che l’attore che autorizza l’invio delle armi abbia sul sostegno nell’indagine condotta per conto di Aspen Italia. Per testare esplicitamente se il sostegno variasse a seconda che ad inviare le armi fosse la NATO, l’UE o l’Italia, nella domanda che chiedeva se l’intervistato “fosse d’accordo o in disaccordo con la decisione di fornire armi al governo ucraino,” si variava casualmente l’attore della decisione. Per un terzo degli intervistati si menzionava l’Unione Europea, per un altro terzo la NATO e un ultimo terzo riceveva il governo italiano. I risultati mostrano come sia la NATO a produrre l’effetto, quantunque modesto, più significativo – ed in senso accrescitivo del sostegno – rispetto all’UE e al governo italiano, il riferimento al quale totalizza il risultato più modesto. Va ricordato che questi dati sono in linea con precedenti rilevazioni che pure chiedevano se si era d’accordo o in disaccordo con l’invio di armi all’Ucraina,  e confermano che un “formato” delle risposte del tipo accordo/disaccordo tende produrre a un numero più alto di persone favorevoli rispetto ad altre formulazioni.  Nel settembre 2002, ad una identica domanda che chiedeva se l’intervistato fosse “d’accordo o in disaccordo con la decisione del governo italiano di fornire armi al governo ucraino,” (indagine IAI-LAPS) il 44% rispondeva di essere molto o abbastanza d’accordo, una variazione non significativa rispetto al giugno dello stesso anno.

*	Combinando queste informazioni, si ottiene che l’unico modo per ottenere una maggioranza di favorevoli all’invio di armamenti all’Ucraina sia quello di non menzionare il governo italiano e di non riferirsi esplicitamente all’invio di armi da parte nostra. E comunque, anche in questo caso, non si riesce nemmeno a raggiungere i due terzi dei consensi, come rivela appunto la distribuzione delle risposte alla domanda dell’Eurobarometro

### Sanzioni

Come è noto, la strategia occidentale di sostegno all’Ucraina prevede, accanto alla assistenza militare, il ricorso alle sanzioni economiche contro la Russia.  Nel periodo tra febbraio 2022 e giugno 2023, il Consiglio Europeo ha lanciato undici diversi pacchetti di misure sanzionatorie, culminate a giugno 2022 con il bando, con alcune limitate eccezioni, alle importazioni di petrolio e di prodotti raffinati (ma non ancora di gas). Le rilevazioni demoscopiche italiane hanno seguito, con le loro domande, la crescente pressione esercitata dalle sanzioni sulla Russia, esplorando in particolare se gli italiani fossero disposti ad inasprirle, in generale o con particolare riferimento al gas e al petrolio e a quali condizioni, esplorando gli effetti dei costi economici e sociali di tali inasprimenti.

#### Gli Italiani e le sanzioni

* L’opinione pubblica italiana è tiepida anche nei confronti delle sanzioni ma, al contrario delle armi, in questo caso vi è una maggioranza relativa di italiani che appoggia tale misura contro la Russia. Si registra tuttavia un leggero calo del sostegno per le sanzioni con il passare del tempo.

Nei primi mesi del conflitto, come riportato dall’Eurobarometro, poco più di due terzi circa degli intervistati italiani era favorevole alle sanzioni economiche contro la Russia. Ad esempio, il 3 marzo 2022 l’EMG indicava un 60% di favorevoli alle “sanzioni contro la Russia,” maggioranza che passava al 65% una settimana dopo e al 67% dopo altri sette giorni. L’indagine Demos&PI del 12 aprile 2022 riportava una percentuale di favorevoli del 70% e il 19 aprile il 70% degli intervistati SWG era favorevole a che l’Italia “impartisca (sic!) sanzioni economiche nei confronti della Russia,” percentuale analoga (69%) a quella della rilevazione SWG del 9-14 marzo. Tuttavia, nel settembre (7-9 settembre) 2022 ad una domanda della Quorum che chiedeva se “dopo tutti questi mesi, lei manterrebbe o toglierebbe le sanzioni alla Russia?” solo il 37% risponde di mantenerle ed un altro 37% di toglierle, con il 26% di indecisi. 

La serie più lunga di domande sulle sanzioni è stata posta da IPSOS e include un esplicito riferimento ai costi. Essa rivela un progressivo – ancorché lento – declino del sostegno per le sanzioni (Figura 2), che passa progressivamente da circa due terzi di intervistati a meno della metà. In linea con questo trend, alla domanda posta da IPSOS il 5 settembre 2022 che chiedeva a chi “oggi le sanzioni economiche comminate alla Russia stanno facendo più male,” il 70% degli italiani intervistati risponde all’Italia e agli altri paesi europei e solo il 14% indica la Russia (con un 16% che non risponde).

*	L’opinione pubblica italiana sembra avere una scarsa fiducia nelle sanzioni

Tra il 23 e il 28 marzo 2022 l’SWG chiese se “le sanzioni imposte alla Russia avranno un effetto molto, abbastanza, poco o per niente forte come deterrente contro future simili invasioni.” Solo il 36% risponde molto o abbastanza forte, il 45% risponde poco e il 19% per niente. All’inizio del conflitto (28 febbraio – 1° marzo 2022) EUROMEDIA chiese ad un campione di italiani se considerassero “le sanzioni fino ad oggi attuate nei confronti della Russia (a livello economico, finanziario, sportivo…) e quelle in programma … efficaci e utili per indebolire la morsa del conflitto da parte della Russia.” Il 45% risponde di sì, il 35% di no e il 20% non risponde. Il 26-28 aprile e di nuovo il 25 maggio EUROMEDIA chiese se “le sanzioni che i paesi occidentali stanno infliggendo alla Russia per l’attacco all’Ucraina, serviranno a far finire la guerra.” Il 41% le riteneva, in entrambe le rilevazioni, “utili ma non decisive,” mentre il 20% inutili e il 18% “pericolose perché inaspriscono e bloccano il dialogo di pace.” Solo il 15% nella prima rilevazione e il 12% nella seconda le ritengono “fondamentali.” 

*	Due aspetti – tra loro fortemente correlati – rendono gli italiani sostanzialmente ambivalenti rispetto alle sanzioni economiche. Da un lato, è diffusa la consapevolezza che senza colpire la principale fonte di reddito dell’economia russa, l’esportazione di materie prime e segnatamente di gas e petrolio, le sanzioni non avrebbero indebolito in maniera sufficiente l’economia di quel paese. Dall’altro lato, la consapevolezza che, così facendo, anche l’economia dei paesi occidentali, e soprattutto dell’Italia, dipendente fortemente dal gas russo per i suoi approvvigionamenti energetici, ne avrebbe sofferto.

Sin dalle prime fasi del conflitto appare chiaro agli italiani che se non si colpiscono i settori nei quali la Russia esporta materie prime energetiche le sanzioni sarebbero state inefficaci. Questa convinzione è manifestata dall’indagine EMG del 9 maggio 2022 che chiede se le sanzioni economiche contro la Russia fossero “giuste ed efficaci,” “giuste ma inefficaci finché non conterranno l’embargo su petrolio e gas” o “sbagliate.” Sebbene solo il 13% le ritenesse sbagliate (e il 22% non rispondesse), la maggior parte dei favorevoli (46%) le ritiene giuste ma inefficaci fino a che non si introduca l’embargo di gas e petrolio) e solo il 19% le reputa “giuste ed efficaci.” E questa consapevolezza è confermata dalla indagine SWG del 23-25 maggio 2022 nella quale il 57% degli intervistati ritiene che “L’Italia e l’UE dovrebbero imporre sanzioni ancora più dure alla Russia.”

D’altro canto, una volta che i costi delle sanzioni – in termini di aumento dei prezzi dell’energia e di inflazione – vengono menzionati, l’entusiasmo per questa misura cala. Purtroppo, non abbiamo alcuna rilevazione nella quale l’effetto della menzione dei costi delle sanzioni energetiche contro la Russia sia stato oggetto di esplicita manipolazione sperimentale, per cui dobbiamo affidarci a comparazioni nel tempo, tra domande diverse. E i dati disponibili sembrano suggerire appunto che la menzione dei costi deprima, seppur leggermente, il sostegno per le sanzioni. Due esempi: il primo ci viene dalle indagini EMG dove il 3 marzo fu chiesto se l’intervistato fosse d’accordo con le “sanzioni contro la Russia” e il 7-9 aprile invece se l’intervistato fosse “favorevole ad un embargo totale del gas e petrolio russi.” A marzo il 60% era favorevole alle sanzioni, ad aprile la percentuale di persone molto o abbastanza d’accordo con l’embargo totale scende al 50%. Il secondo esempio è tratto da una indagine Demos&PI dell’11-12 aprile, nella quale fu chiesto all’intervistato se fosse favorevole o contrario a una serie di “azioni dell’Italia e degli italiani” fra le quali “le sanzioni economiche contro la Russia” e “la rinuncia totale al gas e alle risorse energetiche provenienti dalla Russia.” Il 70% degli intervistati si dichiara favorevole alle sanzioni contro il 59% di favorevoli alla rinuncia totale al gas russo. 

Tuttavia, vi sono altre indagini che suggeriscono una maggiore disponibilità degli italiani a sopportare le conseguenze di un embargo totale sul gas e petrolio russo. A settembre, EMG chiese se “Di fronte all’impennata del prezzo del gas secondo lei bisognerebbe togliere le sanzioni economiche alla Russia.” Il 50% risponde di no, il 30% di sì e il 20% non si pronuncia. E il 28 marzo 2022, ad EMG che chiedeva se l’intervistato “sarebbe disposto a rinunciare alle forniture di gas russo, privandosi di energia elettrica e/o riscaldamento per qualche ora al giorno, pur di dare un chiaro segnale di condanna all’aggressione contro l’Ucraina,” il 34% si dichiara pronto a questa rinuncia, a fronte di un 50% di contrari e un 16% di indecisi. Analogamente, il 30% degli intervistati dalla NOTO sondaggi il 4-5 aprile 2022 dichiara di essere pronto a “non poter usare gas ed energia in alcune ore della giornata” per effetto del razionamento imposto dalle sanzioni energetiche. 

* La disponibilità a sopportare i costi delle sanzioni energetiche dipende dagli argomenti usati per giustificare il mantenimento o il ritiro delle sanzioni.

Termometro Politico tra il 30 agosto e il 2 settembre ha chiesto se “Di fronte all'impennata del prezzo del gas e dell'inflazione, secondo lei si dovrebbero togliere le sanzioni alla Russia?” Il 44% degli intervistati di fronte a questa domanda, che esplicita alcune possibili conseguenze delle sanzioni per gli italiani, risponde di no, sulla base di due argomenti offerti nelle risposte – “vorrebbe dire cedere a un ricatto. Anzi, dovremmo essere più duri con Mosca” e “sarebbe un cedimento. Le sanzioni devono rimanere al livello attuale” – mentre il 23% risponde di sì perché è opportuno “rivedere l’atteggiamento verso la Russia” e il 28% ritiene che “non avremmo dovuto imporre alcuna sanzione fin dall'inizio.” 

Due domande, poste da IXE e da QUORUM ai primi di settembre, e che contestualizzano con argomenti diversi le ragioni per le sanzioni, suggeriscono quanto sensibile al framing siano le risposte degli italiani su questo punto. Da un lato, IXE, tra il 29 agosto e il 2 settembre 2022, chiede se la scelta di imporre le sanzioni sia giusta, premettendo che “L'Italia, insieme ad altri Paesi dell'Unione Europea, ha deciso di imporre pesanti sanzioni economiche (blocco delle banche e del commercio) alla Russia, allo scopo di indebolirla e di accentuare le fratture al suo interno per fermare il conflitto.” In questo caso, il 66% degli intervistati risponde che è giusta e solo il 30% la ritiene una decisione ingiusta. Invece quando, come in QUORUM il 2-4 settembre 2022, si chiede se sia stato giusto imporre le sanzioni a Mosca, premettendo che “le sanzioni alla Russia per l’aggressione all’Ucraina hanno portato a ritorsioni, anche sulla fornitura di gas,” solo il 43% la ritiene una scelta giusta, il 37% sbagliata e il 20% non risponde. Pochi giorni dopo QUORUM reiterò la domanda, chiedendo se fosse giusto imporre le sanzioni considerando che “hanno portato a un forte innalzamento dei prezzi:” in questo caso, il 43% risponde di ritenerle giuste, il 34% sbagliate e il 24% non risponde.

### Intervento militare

*	La maggioranza assoluta degli italiani è contraria ad un intervento diretto del nostro paese nel conflitto e tale orientamento resta costante nel tempo, anche se la ampiezza varia a seconda dell’oggetto della domanda: se cioé si parli del coinvolgimento di truppe NATO o italiane. 

Diverse domande hanno esplorato il tema dell’intervento militare nel corso dei mesi, generalmente, e in maniera costante nel tempo, maggioranze assolute si sono dimostrate contrarie ad un intervento diretto nel conflitto di qualsiasi tipo e con qualsiasi modalità. Si osservano differenze rilevanti nell’ampiezza del fronte di chi si dice contrario – e, di conseguenza, anche di chi si dice favorevole – nell’eventualità in cui la domanda posta indaghi un eventuale intervento di truppe NATO, ovvero domandi esplicitamente o sottintenda un intervento di truppe italiane. Il 59% degli intervistati da EMG il 1° Marzo si dice contrario ad un intervento delle nostre truppe a fianco di quelle NATO, mentre il 22% sarebbe favorevole; sempre a Marzo indagando circa un intervento diretto con i propri militari il 72% degli intervistati di Noto Sondaggi si dichiara contrario contro al 15% di favorevoli. Similmente, il 10 Marzo il 78% degli intervistati da IPSOS circa un intervento di truppe italiane si dichiara contrario, il 15 Marzo solo 62% degli intervistati EMG circa un intervento di truppe NATO si dichiara dello stesso avviso.

### Ingresso alla NATO e all’UE

*	Quando si chiede agli intervistati la propria posizione circa l’ingresso dell’Ucraina nella NATO e nell’Unione Europea, si osserva che maggioranze significative prospettano tendenzialmente di procrastinare le decisioni nel tempo; che maggioranze crescenti siano contrarie all’ingresso nella NATO, e timidamente favorevoli all’ingresso nell’UE e che, tendenzialmente, gli italiani  siano più favorevoli ad un ingresso nell’Unione Europeo rispetto che nella NATO.

L’indagine SWG del 2-4 Marzo dimostra come maggioranze robuste siano favorevoli all’ingresso dell’Ucraina nell’UE (71%), ma come, allo stesso tempo, la medesima riflessione non possa essere fatta sull’adesione alla NATO: solo il 54% degli intervistati si dichiara favorevole, mentre il 36% è contrario. Nell’indagine dell’Euromedia Research del 27-28 Aprile sebbene il 40% degli intervistati sia contrario all’ammissione dell’Ucraina nell’UE una maggioranza relativa si dimostra comunque favorevole (42%), contemporaneamente sul fronte dell’adesione alla NATO, il 48% degli intervistati si dichiarano contrari e soltanto il 31% si dimostra invece favorevole. 

* Quando si indaga la posizione degli intervistati circa l’adesione dell’Ucraina alla NATO, si osserva che il numero di soluzioni alternative poste agli intervistati incide sulle timide maggioranze inizialmente favorevoli e che, davanti alla possibilità di un’adesione in tempi rapidi, maggioranze solide si dichiarino apertamente contrarie.

Se nel sondaggio SWG del 16-18 Febbraio il 33% degli intervistati si dichiara favorevole ad un’eventuale adesione dell’Ucraina alla NATO, mentre il 27% contrario, nel sondaggio del 15-17 Febbraio del Termometro Politico, ponendo il campione davanti a un set di scelte composito e più articolato, il 54% si dichiara contrario all’adesione, allo stesso tempo solo il 18% è favorevole, mentre il 22% lo potrebbe essere ma rimandando di alcuni anni la discussione. Indagando invece l’opinione circa un ingresso in tempi rapidi dell’Ucraina nella Nato, il 48% degli intervistati dall’Euromedia Research si dichiara contrario e solo il 31% favorevole.

* Quando si indaga la posizione degli intervistati circa l’adesione dell’Ucraina all’Unione Europea, si osserva che il numero di soluzione alternative poste agli intervistati incide sulla composizione delle maggioranze che si dichiarano favorevoli e che, davanti alla possibilità di un’adesione in tempi rapidi, le iniziali maggioranze solide si affievoliscano.

Se il 71% degli intervistati SWG del 2-4 Marzo si dichiarava apertamente favorevole all’ingresso dell’Ucraina nell’Unione Europea, osservando la composizione della maggioranza nel campione del Termometro Politico del 1-3 Marzo, che propone un set di risposte più numeroso e articolato, si evince come il 16% degli intervistati sia favorevole, il 30% lo accetti come atto simbolico rimandando però la decisione ufficiale, il 28% posporrebbe la decisione di un paio di anni e il 24% sarebbe contrario a prescindere. L’iniziale forte sostegno decresce significativamente se ad essere indagata è un’adesione nell’UE in tempi stretti da parte dell’Ucraina: solo il 42% degli intervistati dall’Euromedia Research (27-28 Aprile) si dichiara favorevole a cui si contrappone un fronte di contrari composto dal 40% degli intervistati.

* Quando si indaga la posizione degli intervistati, in chiave comparata con altri 6 paesi, circa l’adesione dell’Ucraina all’Unione Europea, si osserva che il campione italiano è tendenzialmente più restio ad un’adesione rispetto alla media generale degli altri paesi e che la percentuale di indecisi sia, all’opposto, tendenzialmente maggiore.

Nell’indagine comparata di Euroskopia dell’8-11 Marzo 2022, si osserva nettamente come l’opinione pubblica italiana, comparata con gli altri paesi indagati, sollecitata sull’eventualità dell’ammissione dell’Ucraina nell’UE, si contraddistingua per una tendenziale e costante indecisione, nonché per un più cauto sostegno all’adesione. La percentuale italiana di chi si dichiara favorevole all’ammissione, al confronto con le altre medie, e con quella generale dei sei paesi sondati, è sempre inferiore. 
Quanto detto vale sia per chi ritiene che l’Ucraina debba essere immediatamente accettata (il 27% della media totale 6 paesi contro il 19% della media italiana), sia per chi ritiene che l’Ucraina debba essere accettata tra un paio di anni (il 30% della media totale 6 paesi contro il 26% della media italiana). 
Infine, comparati con tutti gli altri casi presi in esame dall’indagine di Euroskopia, gli intervistati italiani si distinguono come quelli che, più di tutti gli altri, manifestano la propria indecisione (27% del campione) circa l’ammissione o meno dell’Ucraina nell’UE (la media totale degli indecisi dei 6 paesi è del 19%): nessun altro paese tra quelli analizzati ha una percentuale di indecisi tanto alta.

### Aumento delle spese militari

* Quando si chiede agli intervistati quale sia la loro opinione sull’aumento della spesa militare, maggioranze solide e costanti nel tempo si dichiarano contrarie.

Nella serie EMG, 22 Marzo – 26 Aprile, la maggioranza degli intervistati, crescente nel tempo, si dichiara contraria all’aumento delle spese militari: dal 48% del 22 Marzo, al 51% del 26 Aprile, passando per il 60% di intervistati contrari il 5 Aprile. Similmente, per i sondaggi IPSOS e Noto Sondaggi del 4-5 Aprile la maggioranza assoluta degli intervistati si dichiara contraria (51%).
Infine, secondo l’indagine IPSOS del 5-7 Settembre, quando agli intervistati viene chiesto di dichiarare quanto siano d’accordo o in disaccordo circa una serie numerosa di proposte su cosa dovrebbe fare Governo e Parlamento, la proposta di aumentare le spese militari è quella che ottiene il minor tasso di consenso.

* Comparando le risposte degli italiani con quelle di altri paesi dell’Unione Europea, si osserva che gli intervistati italiani mostrnao il più basso tasso di sostegno ad un aumento della spesa militare.

Quando agli intervistati viene chiesto se il proprio paese dovrebbe spendere più risorse sulla difesa a seguito del conflitto Russo-Ucraino, anche a discapito di altri settori quali l’educazione, la salute e la sicurezza interna, l’opinione pubblica italiana si dimostra fortemente contraria. Nella media complessiva l’Italia, infatti, si classifica all’ultimo posto nell’indagine comparata di Datapraxis & YouGov, ECFR (promossa dal 28 Aprile al 6 Maggio) preceduta da Polonia, Svezia, Germania, Finlandia, Francia, Romania, Gran Bretagna, Spagnae  Portogallo. 

### Esercito europeo

*	Maggioranze assolute e costanti nel tempo si dichiarano d’accordo con l'idea della creazione di un esercito europeo, sebbene, nell’eventualità in cui agli intervistati vengano poste diverse e alternative soluzioni, il fronte del consenso si sgretoli. 

Il 57% degli intervistati da SWG tra il 2 e il 7 Marzo si dichiarano molto o abbastanza d’accordo con la creazione di un unico esercito europeo, similmente, sempre il 57% degli intervistati da Demos&Pi e Demetra dell’11-12 Aprile si dichiarano favorevoli rispetto alla possibilità di creare un esercito europeo. Tali maggioranze non sono però confermate nell’analisi del Termometro Politico del 15-17 Marzo, dove solo il 43% risponde affermativamente alla creazione di un esercito unico, il 22% insiste invece sulla collaborazione mantenendo le rispettive distinzioni e il 31% si dichiara contrario. 

Infine, il *wording* delle domande sembra avere un effetto sulle risposte: quando una domanda usa il termine “esercito dell’Unione Europea” al posto di “esercito unico europeo” la percentuale di coloro che accoglierebbero positivamente l’iniziativa è pure maggiore del 57% sopracitato: il 63% degli intervistati di Demopolis il 17-18 maggio dichiarano infatti l’iniziativa come positiva.


[Appendice](https://github.com/LucianaFazio/Ucrania/blob/main/PDF_Appendice/V.%20Cosa%20dobbiamo%20possiamo%20fare%20noi%20v.5.pdf)












