# GLI EFFETTI DELLA GUERRA

## Formulazione delle domande

Il tema degli effetti della guerra è stato esaminato dai sondaggi italiani sotto tre diversi punti di vista. 

* a) Il primo è quello attinente agli effetti economici, siano questi causati direttamente o indirettamente dal conflitto russo-ucraino. Rilevano qui le opinioni degli intervistati circa la possibilità che la guerra influenzi la propria situazione economica, circa i risvolti sulle politiche nazionali e sovrannazionali e circa i maggiori timori per le ricadute economiche della guerra in Ucraina. In questa tipologia di domande il *wording* assume un ruolo significativo.

* b) Un secondo punto di vista attiene invece al fenomeno dell’immigrazione, regolare e irregolare, e ai flussi migratori generati dal conflitto. Sono qui racchiuse le opinioni degli intervistati circa l’accoglienza e l’inserimento nella società italiana dei profughi ucraini, le differenze con “altri” profughi nonché un’indagine comparata con altri sei paesi sulle dimensioni del fenomeno migratorio. 

* c) Il terzo è relativo al sostegno all’Unione Europea e di come questo abbia subito mutamenti e variazioni nel corso dei mesi. Sono qui raccolte le opinioni degli italiani circa il sostegno alla causa ucraina vista con occhi internazionali, le valutazioni sulle responsabilità europee nel conflitto, la richiesta di maggiore indipendenza da logiche americane, e la soddisfazione, ovvero l’insoddisfazione, rispetto alla gestione della crisi da parte delle istituzioni europee.

## Principali risultati 

### VI.1 Effetti Economici

* Solide maggioranze costanti nel tempo evidenziano timori in relazione alla propria situazione economica e quella della propria famiglia. Con il passare del tempo le preoccupazioni per gli effetti economici appaiono maggioritarie. 

L’87% degli intervistati EMG il 1° Marzo 2022 afferma che il conflitto in atto influenzerà la propria vita o quella della propria famiglia. Osservando la composizione del campione nella struttura della maggioranza assoluta, si può osservare come i timori per i risvolti economici siano i secondi ad emergere (37%) subito dopo quelli relativi ad un eventuale conflitto mondiale (38%). A fine marzo, però, per il 59% degli intervistati EMG le conseguenze economiche assurgono al ruolo di preoccupazione più sentita per il campione coinvolto, ben maggiori rispetto ai timori iniziali di un eventuale conflitto mondiale (40%). Ciò è infine ribadito anche dal 48% degli intervistati IPSOS l’11 aprile 2022 contro il 43% di chi ritiene preoccupante un coinvolgimento militare del nostro paese. Ancora, a dicembre 2022 il 56% degli intervistati da Euromedia Research (20-22 dicembre) si dichiara pessimista rispetto ai prossimi mesi, pensando alla situazione economica della propria famiglia.

*	La maggioranza assoluta degli italiani è convinta che il conflitto in atto possa influenzare la propria situazione economica mentre maggioranze leggermente inferiori rispondono che il conflitto in corso abbia *già* influenzato la propria situazione economica. 

Interrogati sugli eventuali effetti economici il 77% degli intervistati da Noto Sondaggi, il 7-8 Marzo 2022, evidenzia come il conflitto in corso possa danneggiare anche la propria situazione economica, parimenti l’80% degli intervistati da Euromedia Research conferma tale posizione. La serie continuata EMG (Marzo-Giugno 2022), indagando la possibilità che la guerra possa influenzare economicamente la vita degli intervistati, dimostra come maggioranze assolute (prossime all’80%) si confermino preoccupate per la propria situazione economica. 

Un’indagine condotta da Noto Sondaggi tra il 4 e il 5 Aprile 2022 propone però un punto di vista diverso: solamente il 62% degli intervistati dichiara di aver registrato e osservato cambiamenti effettivi della propria situazione economica. A conferma di ciò e a distanza di mesi si osservi che per l'81% degli intervistati da di Tecnè, a maggio 2023 (14-15 maggio), la guerra in corso porta ripercussioni dirette sulla propria economia. 

* La crescita dei prezzi è la preoccupazione più stringente tra gli intervistati anche se la responsabilità di essa non è ricollegata alla guerra in atto.

Il sondaggio EMG dell’8 Marzo 2022 evidenzia come tra gli intervistati la crescita dei prezzi sia a tutti gli effetti la preoccupazione maggiore tra le possibili ricadute economiche scaturite dal conflitto (addirittura il 50% degli intervistati conferma questa preoccupazione come quella più critica). Col passare dei mesi la preoccupazione non diminuisce ma, all'opposto, aumenta: la domanda IPSOS del 20-22 dicembre 2022 dimostra che ben il 79% degli intervistati si dichiari molto o abbastanza preoccupato dall'aumento dei prezzi. Il sondaggio IPSOS del 14 Marzo 2022 però evidenzia come per gli intervistati la crescita dei prezzi in Italia non sia dovuta tanto alla guerra (16% del campione), bensì sia causata dall’azione speculativa degli imprenditori (57% degli intervistati), ciò è in parte confermato dalla domanda posta da Bidimedia a dicembre (17-19 dicembre 2022) con la quale si indagano gli eventi dell'anno appena trascorso che hanno influenzato maggiormente le vite degli intervistati: la guerra in Ucraina è solo al 4° posto (12% degli intervistati), il Covid al secondo posto (21%) e l'inflazione – slegata dalla guerra – al primo posto (29%).

### VI.2 Effetti migratori

* Maggioranze solide si dichiarano favorevoli all’accoglienza in generale e agli aiuti umanitari, ma allo stesso tempo solo una minoranza degli intervistati si dichiara disponibile all’accoglienza diretta, alla copncreta integrazione dei migranti, ovvero alla concessione di ulteriori aiuti economici.

Tendenzialmente gli italiani si dimostrano disponibili all’accoglienza dei profughi che scappano dalla guerra in Ucraina. L’indagine del 26 aprile 2022 di EMG dimostra che il 68% degli intervistati il 21 aprile e il 72% degli intervistati il 28 aprile siano favorevoli all’accoglienza in Italia dei rifugiati provenienti dall’Ucraina. Quando agli intervistati viene chiesto però di un’eventuale inserimento degli stessi nella nostra società, le percentuali solide iniziali si riducono: solo il 58% degli intervistati da Euromedia Research l’11 e il 12 marzo 2022 si dichiarano favorevoli.

Tuttavia, solo un italiano su quattro dichiara di aver contribuito ad una raccolta di beni o fondi per i profughi ucraini (sondaggio IPSOS dell’8-9 marzo 2022 (24%) e sondaggio SWG del 16-18 marzo 2022 (24%)), e pochi si dichiarano favorevoli ad accogliere direttamente in casa propria i profughi, o a svolgere attività di volontariato: il 77% degli intervistati da SWG (16-18 marzo 2022) dichiara che non è disponibile all’accoglienza diretta, il 72% dichiara che non ha svolto e non ha intenzione di svolgere attività di volontariato, sia questo nell’assistenza e nell’accoglienza o sanitaria/psicologica. Il 55% è poi contrario a nuove donazioni economiche.

In sintesi, gli italiani si dimostrano tendenzialmente disponibili all’accoglienza, ma solo se questa non implica eccessivi oneri (economici e sociali) per la comunità. Il sondaggio SWG del 16-18 marzo 2022 infatti dimostra come il 43% degli intervistati si dichiari favorevole al sostegno dei profughi ucraini che stanno in Polonia, Moldavia e Romania, ma solo il 29% del campione si dichiara a sua volta pronto ad accogliere in Italia un maggior numero di rifugiati. Il contrasto all'immigrazione, infatti, sebbene registri un leggero declino tra le proprità degli intervistati tra ottobre e novembre 2022 (EMG), permane una politica ampiamente condivisa dalla maggioranza assoluta degli intervistati (il 69% del campione ad ottobre 2022 e il 64% a novembre dello stesso anno).

* In chiave comparata, gli italiani sono i meno disponibili ad accogliere nel nostro paese i rifugiati (di guerra) in quantità maggiore e si caratterizzano per avere il più alto tasso di indecisi.

Il caso italiano nell’indagine di Euroskopia, condotta in sei paesi europei tra l’8 e l’11 marzo 2022, si contraddistingue sotto molteplici aspetti. Il nostro paese si caratterizza per essere un *outlier* in relazione al tasso di indecisi: non solo vanta la percentuale più alta tra chi non sa rispondere (22%), ma tale percentuale è addirittura il doppio rispetto a quella relativa alla media dei sei paesi (11%). 
Il caso italiano si caratterizza altresì come il paese dove si registra il più basso tasso di risposte nella categoria “maggiore quantità di rifugiati” (media italiana del 24% contro una media complessiva dei sei paesi del 38%). Ciò non vuol dire che gli italiani siano favorevoli a una riduzione del numero di rifugiati, bensì che siano i meno propensi ad un loro aumento.

### VI.3 Effetti sul sostegno per l'integrazione europea

* Maggioranze assolute e crescenti nel tempo rivendicano una maggiore indipendenza dell'Unione Europea dalle posizioni americane, nonché un minor protagonismo nei teatri europei degli interessi USA. 

Per il 53% degli intervistati SWG tra il 2 e il 4 Marzo 2022 l’Unione Europea dovrebbe orientarsi ad una politica estera unitaria e indipendente dalle altre super potenze globali. La medesima posizione è confermata a un mese di distanza da un’altra indagine SWG. Il sentimento di indipendenza dal blocco americano è sottolineato da altre due indagini: la domanda del 13 aprile 2022 del Proger IndexResearch, secondo la quale per il 50% degli intervistati l'Europa dovrebbe prendere una posizione diversa da quella degli Stati Uniti in merito al conflitto russo-ucraino; e la domanda EMG del 10 Maggio 2022: per il 62% degli intervistati l’Europa dovrebbe rivendicare, nel conflitto, una maggiore autonomia rispetto agli Stati Uniti. Questa tendenza è confermata, altresì, dalla domanda del Termometro Politico del 10-12 maggio 2022: secondo il 52% degli intervistati l’UE non si sta impegnando abbastanza per favorire la pace in Ucraina perché è troppo succube degli Usa, i quali, all'opposto, ambiscono ad una prosecuzione della guerra. Infine, una domanda di Euromedia Research del 12 aprile 2023 dimostra quanto la tendenza qui descritta non rappresentasse un'opinione estemporanea: ancora, a distanza di quasi un anno dall'ultimo sondaggio qui riportato, il 55% degli intervistati ritiene che l'Europa sia "vassalla degli Stati Uniti"; allo stesso tempo, e a conferma di ciò, nella domanda del Termometro Politico dell'11-12 aprile 2023 il 71% degli intervistati risponde affermativamente alla richiesta del presidente francese Macron sulla maggiore indipendenza dell'UE dagli USA, solo l'11% del campione ritiene invece opportuno il legame attuale con gli USA. 

* Maggioranze crescenti nel tempo manifestano malumori crescenti nei confronti delle istituzioni europee in merito alla gestione della crisi ucraina. Se inizialmente la maggioranza si riteneva soddisfatta dell'operato europeo, col passare dei mesi questa soddisfazione gradualmente si assottiglia: maggioranze crescenti (fino ad arrivare a diventare maggioranze assolute tra gli intervistati) si dichiarano insoddisfatte dell’operato complessivo delle istituzioni europee nella gestione del conflitto.

Il 47% degli intervistati dall’Euromedia Research tra Febbraio e Marzo 2022 si ritenevano soddisfatti di come le istituzioni europee avessero reagito alla crisi ucraina, nella stessa domanda il tasso degli insoddisfatti era pari al 34% del campione. A distanza di tre mesi però la situazione cambia radicalmente: ben il 60% degli intervistati dal Proger IndexResearch a Maggio 2022 dichiarano di essere poco o per nulla soddisfatti dell'operato dell'Europa rispetto al conflitto russo/ucraino, contro il 28% che invece si ritiene molto o abbastanza soddisfatto. A sostegno di ciò a Marzo 2022 il 53% degli intervistati SWG dichiara che la risposta europea all’attacco russo sia stata troppo debole. 
A distanza di circa un anno da quest'ultimo sondaggio, in una domanda del Termometro Politico del marzo 2023 (28-30 marzo 2023), per il 52% degli intervistati l'Unione Europea è peggiorata nel corso degli ultimi anni, per il 35% è rimasta uguale e solo per il 13% è invece migliorata.

Secondo l’opinione pubblica italiana l’Unione Europea non solo avrebbe dovuto impegnarsi maggiormente in un ruolo di mediazione per raggiungere al più presto una tregua (così come evidenziato dal 68% degli intervistati da Demopolis tra il 17 e il 18 maggio 2022), ma avrebbe dovuto altresì impegnarsi in maggior misura per prevenire il rischio del conflitto: secondo il 68% degli intervistati a Marzo 2022 da Noto Sondaggi l’UE ha operato male, ha sottovalutato i rischi e non è stata molto incisiva nelle prevenzione della guerra.

La sfiducia nelle istituzione europee è possibile ravvisarla altresì nella domanda comparata di SWG che analizza le risposte degli intervistati tra il 1999 e il 2022: la tendenza all’integrazione tra i paesi europei subisce una battuta di arresto e anzi perde consenso in termini percentuali: -8%; la tendenza al sovranismo, all’opposto, cresce di 8 punti percentuali in 23 anni. L’appartenenza dell’Italia all’UE, se nel 1999 era ritenuta dal 64% degli intervistati un vantaggio, nel 2022 solo il 34% sono della stessa opinione. Infine, ancora a febbraio 2023 (20-22 febbraio), in una domanda posta da Demos&Pi e Demetra, solo il 38% degli intervistati dichiara di nutrire "molta o moltissima fiducia" nell'Unione Europea.

*	Maggioranze solide ritengono che nessuno degli attori coinvolti nel conflitto sia un valido candidato a mediare tra i poli opposti per raggiungere la conclusione della guerra.

Per il 28% degli intervistati EMG del 18 Aprile 2022 l’UE è l’attore che più di altri sta dimostrando di volere davvero una soluzione diplomatica. Il secondo attore più credibile è l’Ucraina con l’8% dei consensi. E' necessario osservare però come per il 44% degli intervistati nessuno tra gli attori proposti (a cui si aggiungono USA e Russia) sta davvero dimostrando di volere una soluzione diplomatica. La stessa domanda posta a distanza di quasi un mese (9 Maggio 2022) indica una soluzione ancora più incerta, soprattutto per l’UE: solo il 21% degli intervistati crede che stia lavorando ad una soluzione diplomatica, mentre la percentuale di chi non ritiene nessun attore credibile resta fissa attorno alla stima precedente (43%).

* Il sostegno iniziale italiano al fronte europeo e alle politiche promosse a livello internazionale per il contrasto della Russia e il sostegno dell’Ucraina sembrerebbe registrare una progressiva erosione con il passare dei mesi. L’opzione di poter cedere territori alla Russia, inizialmente valutata come impossibile, con il passare dei mesi è cresciuta fino a diventare l’opzione preferita dalla maggioranza (relativa) degli intervistati. 

A Giugno 2022 (24-25) il 58% degli intervistati Winpoll sono poco o per nulla d’accordo con le politiche europee di imporre sanzioni alla Russia e inviare armi all’Ucraina. Sempre a Giugno, secondo un’indagine del Termometro Politico, solo per il 16% degli intervistati l’Italia e i paesi occidentali dovrebbero preoccuparsi della causa ucraina, inviando armi (14% di quel 16%) o scendendo direttamente a fianco dell’Ucraina militarmente (2% di quel 16%). Per il 17% del campione l’occidente non dovrebbe preoccuparsi della questione, mentre il 35% degli intervistati (maggioranza relativa nel campione) i paesi occidentali dovrebbero consigliare all'Ucraina di cedere parte del territorio alla Russia in cambio della pace e della sicurezza.

[Appendice](https://github.com/LucianaFazio/Ucrania/blob/main/PDF_Appendice/VI.%20Gli%20effetti%20del%20conflitto%20v.3.pdf)
