# IL CLIMA DI OPINIONE

## Formulazione delle domande

* La sezione 7.2.1 indaga la posizione degli italiani circa l’intervento e il ruolo della NATO e dell’ONU, le opinioni sulle considerazioni dell’ANPI e, soprattutto, rileva da che parte stiano gli italiani nel conflitto in corso. Questo ultimo punto è quello più ricco di dati e viene osservato a sua volta sotto un duplice profilo: da un lato viene indagata l’opinione degli intervistati circa la posizione mantenuta dagli italiani, dall’altro lato viene invece chiesto direttamente agli intervistati da quale delle due parti del conflitto essi propendano. 

* La sezione 7.2.2 raccoglie invece domande riguardanti la simpatia e la stima nei confronti dei Presidenti di Russia ed Ucraina, nonché quelle relative alla legittimità della partecipazione di Putin a summit internazionali (G20) ovvero all’opportunità di un dialogo con lo stesso.

## Principali risultati 

### Cosa pensano gli (altri) italiani della guerra

* Maggioranze assolute ma decrescenti nel tempo ritengono che gli italiani stiano dalla parte dell’Ucraina.

La serie temporale IPSOS, che indaga il clima di opinione, evidenzia che a marzo 2022 (28-30 marzo) il 64% degli intervistati si dicevano convinti che gli italiani stessero dalla parte dell’Ucraina, la stessa posizione cala progressivamente fino ad ottobre 2022 (11-12 ottobre) dove si registra una percentuale poco al di sopra della maggioranza assoluta (51%). Allo stesso tempo resta stabile (e minoritario) il fronte di chi crede che gli italiani stiano dalla parte della Russia, con percentuali quasi costanti intorno al 19%. Consequenzialmente, a crescere nel corso dei mesi è la quota di coloro che ritengono che gli italiani non siano da “Nessuna delle due parti,” che passa dal 17%  al 30% in setti mesi. 

* Deboli maggioranze – prima assolute poi relative – decrescenti nel tempo si schierano dalla parte dell'Ucraina. Contestualmente maggioranze crescenti nel tempo si rifiuta di prendere posizione.

La serie temporale IPSOS, indagante le posizioni degli italiani tra fronte russo e ucraino, rileva che a marzo 2022 (28-30 marzo) il 57% degli intervistati si posizionava apertamente a favore dell’Ucraina. Tale sostegno decresce progressivamente fino ad eguagliare la percentuale di coloro che non si dichiarano sostenitori di nessuna delle due parti a giugno 2022 (28-29 giugno ambedue pari al 46%). Ad  ottobre 2022 (11-12 ottobre) si registra il tasso più basso tra i sostenitori del fronte ucraino (43% di intervistati) contro il valore massimo tra chi non vuole prendere una posizione (50% degli intervistati). Da ottobre 2022 a febbraio 2023 cresce nuovamente il fronte di chi si dichiarta sostenitore dell'Ucraina – senza mai tornare a maggioranza assoluta – e decresce lievemente il fronte dei neutralisti attestandosi, a febbraio 2023, rispettivamente al 47% e al 46% del campione. 

Infine, aumentano nel corso di 11 mesi – seppur di poco – i sostenitori della Russia attestandosi intorno al 7% a febbrai 2023 (20-23 febbraio) in linea, per altro, con le indagini poste nel corso dell’anno circa la simpatia e il gradimento della figura di Putin.

* Osservando le divergenze tra le due precedenti indagini si osserva che la percentuale effettiva di sostenitori dell’Ucraina e della Russia sia sovrastimata dagli intervistati e che, di conseguenza, risulti significativamente sottostimata la percentuale di coloro che non stanno né dalla parte della Russia né dalla parte dell’Ucraina.

La comparazione tra le due sequenze mostra che a marzo 2022 (28-30 marzo) vi fosse una divergenza di 7 punti percentuali tra chi sostiene effettivamente l’Ucraina e chi crede che il popolo italiano sostenga in maggioranza l’Ucraina (il 57% di intervistati schierati a favore dell’Ucraina a fronte del 64% che ritiene gli italiani presunti tali). Sulla stessa linea, ma ancora più marcato (14 punti percentuali) è il distacco tra chi sostiene la Russia (5%) e gli intervistati che credono che gli italiani stiano dalla parte della Russia (19%). Risulta invece nettamente sottostimata la percentuale di coloro i quali non prendono una posizione (38%) rispetto alla percentuale di intervistati che ritengono che gli italiani in maggioranza non prendano una posizione (17%), un divario di ben 21 punti percentuali.

È interessante osservare come lo stesso confronto fatto ad ottobre (11-12 ottobre 2022) ci offre nuovamente una divergenza per tutte e tre le posizioni osservate mantenendo gap percentuali tra i sostenitori effettivi e i presunti tali quasi costanti, nonostante le variazioni intercorse all’interno di ciascun gruppo: i sostenitori presunti dell’Ucraina decrescono, ma decrescono anche i suoi sostenitori effettivi.

In conclusione, le due serie IPSOS rivelano che vi siano molti più italiani che non si sono schierati da nessuna delle due parti rispetto a quelli che la gente pensi. Al contrario, il numero di sostenitori effettivi di ambedue gli schieramenti sono in diversa misura sovrastimati dagli intervistati. 

* La maggioranza assoluta degli italiani è contraria a quanto gli Stati Uniti abbiano fatto sinora per il conflitto.

Come in parte anticipato nel capitolo precedente (6.3):la maggioranza degli intervistati si dichiara contraria all’attività posta in essere dagli Stati Uniti e buona parte dell’opinione pubblica ritiene altresì che gli stessi, nel conflitto in corso, promuovano esclusivamente i propri interessi. Ciò è quanto emerge dall’indagine di SWG svolta tra il 6 e l’8 aprile 2022: il 57% degli intervistati, infatti, sostiene che gli USA difendono solo i propri interessi, la medesima percentuale sale al 65% a maggio nell’indagine IPSOS. Quanto detto è in parte ribadito dall’indagine di Proger IndexResearch il 13 aprile 2022: il 46% degli intervistati boccia la gestione della guerra da parte di Biden e della Nato, contro il 35% degli intervistati che invece la approva. Infine, nella valutazione di IPSOS dell’8-9 Marzo 2022 il Governo USA è terzultimo, dietro a Cina e Russia, per numero di voti negativi circa la gestione del conflitto. Si osservi infine che a marzo 2023, interrogati sul tentativo di mediazione da parte della Cina da Proger Index Research, il 57% degli intervistati di dichiara favorevole, il 15% non sa o non vuole rispondere e soloil 28% lo ritiene inutile.

### Simpatia per l’Ucraina e la Russia e giudizi di rispettivi leader

* Cresce nel tempo il numero di coloro che hanno sentimenti negativi per Putin.

A febbraio 2022 il 36% degli intervistati dal Termometro Politico dichiara di avere una buona considerazione del Presidente Putin (il 26% da sempre e il 10% da poco), il 42% dichiara che non lo stima e non l’ha mai stimato, mentre il 12% ha recentemente invece cambiato idea su di lui, in peggio. A marzo dello stesso anno solo il 19% degli intervistati SWG mantiene una buona opinione su Putin, contro il 66% degli intervistati che invece dichiarano di avere una pessima considerazione del Presidente della Russia (definendolo un criminale, ovvero un pessimo statista). Ciò è perfettamente coerente con quanto emerso nel paragrafo precedente sulle considerazioni delle posizioni degli italiani. Questa stima è altresì in linea con l’indagine SWG condotta tra il 27 aprile e il 2 maggio del 2022 secondo la quale il 64% degli intervistati sperano che Putin perda la guerra. Sembrerebbe quindi delinearsi un’associazione tra la reputazione del Presidente Putin e i posizionamenti dell’opinione pubblica italiana contraria allo schieramento russo. Con il nuovo anno la situazione sembra confermare le posizioni trovate: nell'indagine IPSOS condotta tra il 10 e l'11 gennaio 2023, il 48% degli intervistati ritenevano la Russia di Putin la maggiore minaccia per il mondo. 

L'indagine Demos&Pi e Demetra condotta tra il 26 e il 27 aprile 2023, evidenzia come l'88% degli intervistati provi "poca o pochissima fiducia" nei confronti della Russia di Putin. La Federazione Russa è il paese che registra il più alto tasso, tra i 9 paesi indagati, di sfiducia, seguita da Cina (81%), Ungheria (77%), Francia (64%) e Ucraina (61%). È utile osservare, dunque, come la maggioranza assoluta degli intervistati nutra "poca o pochissima fiducia" anche nei confronti dell'Ucraina di Zelensky.

* Maggioranze robuste si dichiarino favorevoli ad un atteggiamento dialogante nei confronti del Presidente Putin, nonostante la sua scarsa popolarità.

Nonostante il clima di opinione pubblica sia tendenzialmente contrario e ostile alla Russia e al suo leader, si osservano maggioranze favorevoli a un dialogo: per il 56% degli intervistati SWG il 13-16 maggio 2022 i paesi dell’Unione Europea dovrebbero mantenere un atteggiamento dialogante verso Putin al fine di cercare un accordo. Questa tendenza è confermata altresì dalle domande sul G20: per il 43% degli intervistati tra giugno e luglio dello stesso anno da SWG, Putin dovrebbe essere invitato al Summit con gli altri paesi (il 20% non si esprime, mentre il 37% è contrario). La stessa opinione è confermata dal 48% degli intervistati dal Termometro Politico nello stesso periodo (maggioranze relativa nel campione indagato), il 30% si dichiara invece contrario. 

* Anche il giudizio nei confronti del Presidente Zelensky non è estremamente positivo

Per il 53% degli intervistati il 28 marzo 2022 da Eumetra srl il leader ucraino non è un vero democratico ovvero è "una pedina nelle mani degli Stati Uniti", per un altro 37% invece è un normale politico che le circostanze eccezionali hanno costretto in una situazione difficile. Solo il 13% degli intervistati ritengono Zelensky un leader. Un'indagine di Tecnè del 14-15 maggio 2023 evidenzia come la maggioranza relativa degli intervistati (46%) continui a non fidarsi del Presidente Zelensky, contro il 34% del campione che invece dichiara di fidarsi.

* Cresce il numereo di italiani che considera tra i paesi “amici” quelli del blocco europeo.

Grazie all’indagine condotta da SWG a Giugno 2020, Giugno 2021 e Aprile 2022 è possibile comparare nel corso di tre anni la simpatia di 800 intervistati circa i paesi considerati “amici” dell’Italia. I dati dimostrano che dal 2020 al 2022 il blocco europeo composto da Francia, Germania e Spagna si è rafforzato a discapito della Russia e degli Stati Uniti. A giugno 2020 la Germania era definita come “amica” dal 9% dei voti, la Francia dal 12% dei voti, la Spagna dal 26%, la Russia dal 14%, mentre gli USA raccoglievano il 22% dei voti. Il “blocco europeo” nel 2020 raccoglieva il 47% dei voti, il blocco non europeo il 53%. Ad Aprile 2022 la Germania raccoglie il 26% dei voti, la Francia il 29%, la Spagna il 23%, la Russia il 2%, gli USA il 21%. Il “blocco europeo” nel 2022 raccoglie il 78% dei voti, il blocco non europeo il 23%.


[**APPENDICE**](https://github.com/LucianaFazio/Ucrania/blob/main/PDF_Appendice/VII.%20Il%20clima%20di%20opinione%20v.3.pdf)
