#  IL RUOLO DEI MEDIA

## Formulazione delle domande 

L'indagine del ruolo dei Media nell’opinione pubblica degli italiani, sebbene sia stata analizzata in un unico capitolo contenente tutte le domande attinenti alla funzione dell’informazione sul conflitto nel nostro paese, è caratterizzata da molteplici punti di vista. È possibile distinguere le domande poste agli intervistati prevalentemente sulla base dell’oggetto indagato, ovvero sulla frequenza temporale con cui queste siano state poste. 

In funzione del contenuto possiamo distinguere pertanto:

* a) Domande che indagano il grado di informazione sulla guerra degli intervistati. Queste domande offrono altresì uno spaccato dell’opinione pubblica sull’efficacia dei media nel raccontare e seguire le fasi del conflitto, sulla capillarità dell’informazione ovvero sull’interesse diffuso nella popolazione a seguire le stesse vicende. 

* b) Domande che ricercano l’opinione degli intervistati sull’opportunità di pubblicare e diffondere immagini sensibili, come il massacro di Bucha. Queste domande indagano altresì il ruolo che i media dovrebbero avere e la condotta che dovrebbero tenere per l’opinione pubblica: agendo da filtro sulla realtà, ovvero trasmettendo con fedele trasparenza i fatti così come questi si presentano. 

* c) Domande che indagano l’opinione degli intervistati sul grado di indipendenza (o partigianeria) dei media, sul ruolo che hanno avuto e che continuano ad avere nella formazione dell’opinione pubblica e, infine, sulla qualità dell’informazione. All’interno di queste tre categorie possono essere fatti ricondurre altresì i sondaggi posti in serie continuata nel tempo del punto d).

* d) Domande poste in serie. Rilevano qua particolarmente i sondaggi IPSOS sul giudizio sull’informazione e sul suo grado di indipendenza-partigianeria, domande sull’opportunità o meno di dare visibilità ad esponenti ufficiali russi. 

## Principali risultati

* Quando si indaga la qualità dell’informazione nell’opinione pubblica, gli intervistati tendono a preferire giornali e telegiornali ai talk show di approfondimento come strumenti di informazione.

Nel sondaggio di Demos&Pi e Demetra dell’11-12 Aprile 2022, su una scala da 1 a 10 circa il tasso di gradimento degli strumenti di informazione,  il 59% degli intervistati esprime una valutazione uguale o superiore a 6 per quanto riguarda la Televisione italiana, mentre solo il 39% ha lo stesso giudizio nei confronti del Talk Show di approfondimento. Questa tendenza è confermata dallo studio SWG del 27-29 Aprile 2022: il 66% degli intervistati ritengono molto o abbastanza affidabili i telegiornali (il 60% per i quotidiani cartacei), tale percentuale si riduce al 39% nei confronti dei talk show. 

* Quando si indaga la qualità dell’informazione, percentuali significative e prossime alla maggioranza assoluta dichiarano che i media non siano stati indipendenti nel raccontare e descrivere il conflitto in corso. 

Solo il 24% degli intervistati dal Termometro Politico del 19-21 Aprile 2022 credono che i media siano stati sinceri ed equilibrati. La restante parte ritiene, all’opposto, che i media abbiano adottato posizioni specifiche per fare più audience (il 13% sostiene che i media abbiano adottato posizioni troppo filo/russe, il 19% posizioni troppo filo/occidentali), la maggioranza degli intervistati però, quasi il 40%, crede che i media manipolino l’informazione pubblica seguendo ordini ricevuti dall’alto. L’informazione che qui rileva maggiormente è che, nel complesso, il 71% degli intervistati non crede che i media abbiano raccontato la verità sul conflitto in corso. 
A sostegno di quanto emerso: sebbene soltanto il 23% degli intervistati da Demos&Pi e Demetra l’11-12 Aprile 2022 ritengano che le notizie e le immagini sui presunti crimini dell’esercito russo siano una montatura del governo ucraino, ben il 46% degli stessi ritengono però che la maggior parte dell’informazione sulla guerra dell’Ucraina, in Italia, sia distorta e pilotata. 

* Quando si indaga nell’opinione pubblica quali, tra quelle proposte, siano le informazioni più credibili, maggioranze significative non ritengono nessuna delle informazioni veritiera, ad eccezione fatta per quelle attinenti disastri umanitari, stragi e genocidi. A ciò può essere in ultima istanza aggiunto il fatto che l’opinione pubblica, sondata dalle domande sugli intervistati, si dichiara costantemente favorevole a un giornalismo senza filtri – compreso nei casi di massacri come quelli di Bucha – nonché a un’informazione indipendente e bipartisan.

Il disegno di un’opinione pubblica scettica, così come tracciato precedentemente è confermato dai sondaggi di SWG svolti tra il 27 e il 29 Aprile 2022. Emerge chiaramente infatti come l’opinione pubblica tenda a credere maggiormente ad eventi correlati a disastri umanitari, massacri o stragi, ma non al numero effettivo di civili coinvolti. Tra le 9 notizie indagate da SWG quelle concernenti i genocidi delle popolazioni sono le uniche, tra tutte quelle proposte, a raccogliere tra gli intervistati una percentuale maggiore tra coloro che ritengono credibili le informazioni date rispetto a coloro che non le ritengono credibili. Il 51% degli intervistati ritengono infatti molto o abbastanza credibili le informazioni sui genocidi, ma solo il 44% mantiene la medesima fiducia circa il numero dichiarato di vittime tra i civili, su questo tema si osserva infatti che la maggioranza relativa degli intervistati (il 46%) dichiarano di non credere ai numeri indicati o di crederci comunque poco. 
Cambiando completamente tema ed indagando l’opinione pubblica circa l’andamento dei negoziati solo il 30% dichiara di crederci, mentre ben il 61% degli intervistati non crede o crede poco alle informazioni date. 

Gli intervistati, nei sondaggi IPSOS e SWG di Aprile (SWG 6-8 Aprile, IPSOS 5-7 e 12-14 Aprile), con percentuali prossime al 50%, si dichiarano favorevoli nel mostrare immagini cruente da parte dei media, gli intervistati contrari fanno registrate percentuali comprese tra il 30% e il 40% del campione. Ciò rafforzerebbe l’idea per la quale l’opinione pubblica italiana desidera un giornalismo senza filtri e trasparente, un’informazione a cui spetta mostrare tutto ciò che accade in un conflitto e che mantenga un comportamento bipartisan nei confronti degli opposti schieramenti.
 
Quest’ultima considerazione è confermata dalla serie continuata IPSOS sulla visibilità concessa nei confronti di rappresentanti ufficiali russi. L’indagine condotta tra Maggio e Giugno mostra come la maggioranza (inizialmente assoluta e successivamente relativa) degli intervistati, sebbene decrescente nel tempo, si dichiari molto o abbastanza d’accordo con l’opportunità di dare visibilità ad esponenti russi sui media nazionali. A rafforzarsi nel tempo, d’altronde, non è il polo di chi si dichiara poco o per niente d’accorso su tale opportunità – che al contrario resta pressocché costante nel tempo –, bensì il polo degli indecisi che dal 22% di Maggio passa al 28% di Giugno.
Tendenzialmente l’opinione pubblica è quindi favorevole ad una partecipazione di esponenti russi sui media nazionali e, più in generale, sul dare spazio nelle televisioni e nei dibattiti a tutte le opinioni coinvolte. Infatti, per il 69% degli intervistati IPSOS del 5 Aprile 2022 è giusto ospitare sui media nazionali entrambi gli schieramenti, questa convinzione non si attenua significativamente neanche nei confronti di membri di spicco dell’entourage putiniana: per il 63% degli intervistati dal Termometro Politico a Maggio è stato giusto ospitare sulla Tv italiana il ministro degli Esteri russo Lavrov.

* Quando si chiede agli intervistati un giudizio sull’indipendenza o la partigianeria dell’informazione italiana, maggioranze relative, solide e crescenti nel tempo segnalano un’eccessiva polarizzazione del dibattito pubblico troppo sbilanciato a favore dell’Ucraina e di Zelensky.

Le domande poste in serie continuata da Ipsos, tra Marzo 2022 e Luglio 2022, indagano l’opinione pubblica sul ruolo che l’informazione italiana ha mantenuto nel corso del conflitto, fotografando 15 distribuzioni di preferenze diverse. Ciò che emerge chiaramente dall’analisi dei dati di sondaggio è che nel tempo si rafforzi, seppur di poco, il già maggioritario polo di chi ritiene che l’informazione italiana sia troppo sbilanciata in favore del fronte ucraino. A Marzo il 37% degli intervistati denuncia un’informazione eccessivamente in favore di Zelensky, il 30% ritiene invece di essere sottoposto a un’informazione neutrale ed oggettiva, mentre solo il 6% ritiene che i media siano troppo sbilanciati a favore della Russia e di Putin. A distanza di 4 mesi il polo di chi sostiene che vi sia un’eccessiva esposizione a favore dell’Ucraina è formato dal 39% del campione (avendo altresì toccato punte del 42% degli intervistati nel corso dei mesi), chi crede di avere a che fare con un’informazione bipartisan si riduce al 26%, mentre l’ultimo fronte aumenta di un punto percentuale (nel corso dei mesi il massimo raggiunto da quest’ultimo schieramento è l’8% del campione).

Queste dinamiche si inscrivono in un contesto, quello italiano, dove la maggioranza degli intervistati nel corso del tempo si dichiara comunque molto o abbastanza informato – il 69% nel campione intervistato Demos&PI e Demetra ad Aprile – ovvero molto o in parte informato – il 72% nell’indagine IPSOS di marzo.

[Appendice](https://github.com/LucianaFazio/Ucrania/blob/main/VIII.%20Ruolo%20dei%20media.pdf)

